### ISSUE TITLE
[Listing Error] Fractal Bridge

### ISSUE THREAD

**Issue by andyhud09** [OctoPrint/plugins.octoprint.org#1006]
### Which Plugin?

https://plugins.octoprint.org/plugins/fractalbridge/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

The Discord invite has expired.

**Comment by foosel** [comment]
Hi @Popeyef5, see above report. Also seems to apply to the invite in your repository's README.

**Comment by foosel** [comment]
@Popeyef5 ping?

**Comment by foosel** [comment]
@FractalManufacturing @Fractal3D see above

**Comment by Popeyef5** [comment]
Hey! Nice catch. Sorry for the late reply, I was AFK for the past few weeks. I'll fix it ASAP. Thanks again!

**Comment by jneilliii** [comment]
Any update @Popeyef5 ?

**Comment by foosel** [comment]
Two years of silence and the website no longer works either. I guess it's time to delist this.
