### ISSUE TITLE
[Listing Error] USB Relay Control

### ISSUE THREAD

**Issue by mdulac1966** [OctoPrint/plugins.octoprint.org#1031]
### Which Plugin?

https://plugins.octoprint.org/plugins/usbrelaycontrol/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

After a fresh Octoprint install the USB relayboard is not found.
The board is working whitin Windows RelayControler it detected a HURTM 2 switches relais board.
Does anyone have an idea how to solve this?

**Comment by jneilliii** [comment]
This issue tracker is for the plugin repository itself, not issues with functionality of the plugin. Please open an issue on the plugin's github repo.
