### ISSUE TITLE
i got an error 5 times tring to install OctoPrint-Wyze & it is not in app  plugins 

### ISSUE THREAD

**Issue by Sparkie01** [OctoPrint/plugins.octoprint.org#1036]
### Which Plugin?

https://plugins.octoprint.org/plugins/wyze/

### What kind of listing error are you reporting?

broken link on the listing

**Comment by jneilliii** [comment]
Please elaborate what you mean? The plugin page loads as well as the homepage link to GitHub without problems for me.

**Comment by cp2004** [comment]
Closing due to lack of response
