### ISSUE TITLE
While trying to install, receive this message, "ERROR: Could not find a version that satisfies the requirement OctoPrint-SlicerSettingsParser (from octoprint-extrafileinfo)ERROR: No matching distribution found for OctoPrint-SlicerSettingsParserError!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output".

### ISSUE THREAD

**Issue by Loadmaster1** [OctoPrint/plugins.octoprint.org#1059]
### Which Plugin?

https://plugins.octoprint.org/plugins/extrafileinfo/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

While trying to install, I receive this message, "ERROR: Could not find a version that satisfies the requirement OctoPrint-SlicerSettingsParser (from octoprint-extrafileinfo)ERROR: No matching distribution found for OctoPrint-SlicerSettingsParserError!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output"

Install fails.

**Comment by jneilliii** [comment]
Please report plugin installation issues in the plugin's repository tracker.

https://github.com/larsjuhw/OctoPrint-ExtraFileInfo/issues
