### ISSUE TITLE
[Listing Error] ExtraFileInfo

### ISSUE THREAD

**Issue by skulldgry** [OctoPrint/plugins.octoprint.org#1061]
### Which Plugin?

https://plugins.octoprint.org/plugins/extrafileinfo/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

ERROR: Could not find a version that satisfies the requirement OctoPrint-SlicerSettingsParser (from octoprint-extrafileinfo)
ERROR: No matching distribution found for OctoPrint-SlicerSettingsParser
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by kantlivelong** [comment]
Dupe #1060
