### ISSUE TITLE
[Listing Error] GPIO Control

### ISSUE THREAD

**Issue by Vyacheslav23** [OctoPrint/plugins.octoprint.org#1067]
### Which Plugin?

https://plugins.octoprint.org/plugins/gpiocontrol/

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

Плагин не работает
![Плагин](https://user-images.githubusercontent.com/28665769/168087637-bbb1490d-77e7-4361-a20d-5f386c98af43.jpg)
![Плагин 1](https://user-images.githubusercontent.com/28665769/168087961-40d9177e-7a99-4af2-b20f-777477ff6126.jpg)
.

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
