### ISSUE TITLE
[Listing Error] GPIO Control

### ISSUE THREAD

**Issue by Vyacheslav23** [OctoPrint/plugins.octoprint.org#1068]
### Which Plugin?

https://plugins.octoprint.org/plugins/gpiocontrol/

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

![Плагин 1](https://user-images.githubusercontent.com/28665769/168113194-2a8d0fd8-7c6a-42f2-9a38-35d9720d13e8.jpg)

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint

**Comment by kantlivelong** [comment]
@Vyacheslav23 be sure to open your issue with the appropriate repo (not here) and provide more info than just a screenshot.
