### ISSUE TITLE
[Abandoned Plugin] OctoPrint-Enclosure

### ISSUE THREAD

**Issue by WalkerRaiden** [OctoPrint/plugins.octoprint.org#1077]
### Which Plugin?

https://plugins.octoprint.org/plugins/enclosure/

### Link to ticket on plugin's issue tracker confirming abandonment

https://plugins.octoprint.org/plugins/enclosure/

**Comment by cp2004** [comment]
> Link to ticket on plugin's issue tracker confirming abandonment

Can you provide a link to somewhere confirming abandonment? An issue asking the question with no response maybe?

**Comment by jneilliii** [comment]
I know for fact this plugin isn't abandoned, the v2 version linked from the range has activity on the dev branch. There is also a discord where there has been some discussion.
