### ISSUE TITLE
[Listing Error] OctoPrint-GpioFanController

### ISSUE THREAD

**Issue by poprhythm** [OctoPrint/plugins.octoprint.org#1090]
### Which Plugin?

https://plugins.octoprint.org/plugins/gpiofancontroller/

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

Summary is "Uses PI GPIO pins to control a variable speed fan with PWM" - pretty sure the PWM should be removed as it doesn't use these pins. Great project BTW!

**Comment by jneilliii** [comment]
You should report this to the plugin repo directly and request the change. The issue tracker here is really used to manage other things and it's the plugin's author responsibility to manage the content of their listing. 

https://github.com/z4gunn/OctoPrint-GpioFanController/issues
