### ISSUE TITLE
[Listing Error] OctoKlipper

### ISSUE THREAD

**Issue by permanent25** [OctoPrint/plugins.octoprint.org#1102]
### Which Plugin?

https://plugins.octoprint.org/plugins/klipper/

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

After installation, it does not connect me to the printer. I use octoprint for windows

**Comment by cp2004** [comment]
> What kind of listing error are you reporting?
a typo in the plugin listing

Where is the typo?

**Comment by osho-m** [comment]
What kind of Error?

**Comment by cp2004** [comment]
I guess there was no typo 🤷
