### ISSUE TITLE
[Listing Error] Mattacloud Beta

### ISSUE THREAD

**Issue by bjoernefar** [OctoPrint/plugins.octoprint.org#1104]
### Which Plugin?

https://plugins.octoprint.org/plugins/mattacloud/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

404 error + certificate failure

**Comment by kantlivelong** [comment]
@dougbrion

**Comment by dougbrion** [comment]
Hi @jneilliii , sorry about this! This plugin is no longer used/maintained and the web address it used to connect to has since been updated. Feel free to remove the plugin (sorry for not seeing the above issue sooner!).
