### ISSUE TITLE
[Listing Error] OctoPrint-TuyaSmartplug

### ISSUE THREAD

**Issue by Guy-Born** [OctoPrint/plugins.octoprint.org#1115]
### Which Plugin?

https://plugins.octoprint.org/plugins/tuyasmartplug/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

Hey, i am having problem installing this plugin.
i get exit code 4294967295.
"metadata generation failed"
could you help me?
![image](https://user-images.githubusercontent.com/100953332/196155644-5daff924-d966-4635-abbd-dfd18caf4622.png)
![image](https://user-images.githubusercontent.com/100953332/196156117-91e2346c-4e22-4636-8885-de4155079476.png)

thank you.

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
