### ISSUE TITLE
[Listing Error] Octoprint Nexus AI

### ISSUE THREAD

**Issue by planetar** [OctoPrint/plugins.octoprint.org#1116]
### Which Plugin?

https://plugins.octoprint.org/plugins/nexus_ai/?utm_source=octoprint&utm_medium=announcements&utm_content=1.8.6

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

Compatibility info lists 

> Operating Systems: Linux, Windows, Mac OS X, FreeBSD

however, the NexusAI-tutorial linked at the plugin-page clear states as a precondition:

A Windows PC with more than 2G memory

and the screenshotted file listing shows .exe and .dll - files.

I think the compatibility info would be more helpful mentioning this limitation instead of promising Linux compatibility that does not exist for the core functionality.

**Comment by jneilliii** [comment]
The plugin itself is completely OS agnostic, and that is the correct compatibility information for that. It's the actual server-side that is currently windows only and I know that the @fiber-punk guys are working to make a linux version as well.
