### ISSUE TITLE
[Listing Error] PSU Control after installing the plugin is not there to use

### ISSUE THREAD

**Issue by sinner1234567890** [OctoPrint/plugins.octoprint.org#1117]
### Which Plugin?

https://github.com/kantlivelong/OctoPrint-PSUControl

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

OctoPrint 1.3.12 running on OctoPi 0.17.0 the plugin donlods but dosnt show up to use.

**Comment by kantlivelong** [comment]
@sinner1234567890 do you have a related ticket on the repo? If not, open one up and provide whatever information you can. The version you are on is quite old but I can't think of any reason why the plugin itself wouldn't work.

**Comment by kantlivelong** [comment]
Closing due to lack of response.
