### ISSUE TITLE
[Abandoned Plugin] Exclude Region

### ISSUE THREAD

**Issue by katiekloss** [OctoPrint/plugins.octoprint.org#1122]
### Which Plugin?

https://plugins.octoprint.org/plugins/excluderegion

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/bradcfisher/OctoPrint-ExcludeRegionPlugin/issues/67

### Is there someone open to adopting it?

@katiekloss

**Comment by jneilliii** [comment]
Thanks @katiekloss for volunteering. Process is pretty straight forward. Fork the plugin to your account, make the changes to bring it up to date and update setup.py with incremented version and create a matching tag/release on your repo. Then check other recent adoption PRs for what kind of changes are required here. Happy to answer any questions.

**Comment by cp2004** [comment]
> Link to ticket on plugin's issue tracker confirming abandonment
> https://github.com/bradcfisher/OctoPrint-ExcludeRegionPlugin/pull/64

I think someone should probably open an issue on the repository to at least make it more explicit that the plugin is abandoned and could be adopted. Sometimes when asked directly people will respond and may transfer ownership for example, making the transition basically seamless. Rather than linking to an old PR, that makes no mention of abandoned status.

**Comment by katiekloss** [comment]
> I think someone should probably open an issue on the repository to at least make it more explicit that the plugin is abandoned and could be adopted. Sometimes when asked directly people will respond and may transfer ownership for example, making the transition basically seamless. Rather than linking to an old PR, that makes no mention of abandoned status.

Good point, updated the original issue with a new one I made in that repo.

**Comment by chunkysteveo** [comment]
It's a beautiful plugin that's got me out of so many holes when printing large plates of parts! I hope someone can pick this up 🙏

**Comment by pneumaticdeath** [comment]
I'm pretty handy with python on the backend, and would love to help.  Please let me know if I can be of assistance.

**Comment by WesMcGee68** [comment]
I have it installed but I'm not too savvy with the plugin and haven't been able to get it set up properly.   Would it be possible to put a walk through on it's setup for the beginners, on the home page??

**Comment by bradcfisher** [comment]
I have not abandoned the plugin, though I have also not had as much free time to maintain it as I'd like lately either.  I do plan to continue working on it as time permits, and have several enhancements planned.

I certainly don't mind @katiekloss creating a fork and releasing a derivative, as that's the open source way and permitted by the licensing.  There's nothing wrong with giving folks choices.

**Comment by bradcfisher** [comment]
To follow up on my previous comment, I would suggest that @katiekloss should instead release a separate plugin under a different name and versioning to avoid confusion.  Proper attribution should also be maintained.

**Comment by jneilliii** [comment]
@bradcfisher, if time is an issue maybe you guys could join forces and you could add @katiekloss to your repo as a maintainer.
