### ISSUE TITLE
[Abandoned Plugin] SettingsGuide

### ISSUE THREAD

**Issue by eprouty** [OctoPrint/plugins.octoprint.org#1131]
### Which Plugin?

https://marketplace.ultimaker.com/app/cura/plugins/Ghostkeeper/SettingsGuide2

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/Ghostkeeper/SettingsGuide/issues/110

**Comment by jneilliii** [comment]
Uh, this isn't related to OctoPrint in anyway so not sure why you are posting this here?

**Comment by eprouty** [comment]
Hah, brain fart, that's why 🤦 

Thanks for cleaning up my mistake!
