### ISSUE TITLE
[Abandoned Plugin] SlicerSettingsTab

### ISSUE THREAD

**Issue by larsjuhw** [OctoPrint/plugins.octoprint.org#1137]
### Which Plugin?

https://plugins.octoprint.org/plugins/SlicerSettingsTab/

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/tjjfvi/OctoPrint-SlicerSettingsTab/issues/5

Python 3 support was requested in June 2020 and never got a response. Safe to say it has been abandoned.

### Is there someone open to adopting it?

@larsjuhw

**Comment by jneilliii** [comment]
@tjjfvi giving you 14 days to respond prior to handing over maintenance of the plugin to larsjuhw and redirecting updates.

**Comment by tjjfvi** [comment]
@jneilliii In a perfect world I'd continue to maintain those plugins, but I haven't, so... if someone else is willing to take it on, that's great; let me know if there's anything I can do to facilitate that

**Comment by jneilliii** [comment]
Thanks for confirming. There's nothing necessary on your end for this thanks to the update check overlays.

**Comment by jneilliii** [comment]
If @larsjuhw hasn't forked your repo yet it would be extremely smooth if you transfer ownership of the repo in it's settings @tjjfvi.

**Comment by larsjuhw** [comment]
@jneilliii I haven’t forked it yet no.

**Comment by tjjfvi** [comment]
> larsjuhw already has a repository in the tjjfvi/OctoPrint-SlicerSettingsTab network  

@larsjuhw Looks like you forked a fork of my repo, so I can't transfer it.

**Comment by tjjfvi** [comment]
I'm also willing to give you admin access on the original repo, if that's useful.

**Comment by larsjuhw** [comment]
> > larsjuhw already has a repository in the tjjfvi/OctoPrint-SlicerSettingsTab network
> 
> @larsjuhw Looks like you forked a fork of my repo, so I can't transfer it.

Forgot about that. Just deleted it, does it work now?

**Comment by larsjuhw** [comment]
@tjjfvi thanks for the help!

**Comment by tjjfvi** [comment]
Do you also want to take over <https://github.com/tjjfvi/OctoPrint-SlicerSettingsParser>? SlicerSettingsTab depends on it.

**Comment by larsjuhw** [comment]
> Do you also want to take over https://github.com/tjjfvi/OctoPrint-SlicerSettingsParser? SlicerSettingsTab depends on it.

I already adopted it: https://github.com/OctoPrint/plugins.octoprint.org/pull/1136 :)

**Comment by jneilliii** [comment]
you won't need to do the notices or update check overlay, just the plugin listing page.
