### ISSUE TITLE
[Abandoned Plugin] DeleteMoveAfterPrint

### ISSUE THREAD

**Issue by CDFcalvin** [OctoPrint/plugins.octoprint.org#1151]
### Which Plugin?

https://plugins.octoprint.org/plugins/DeleteAfterPrint/

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/issues/28#issuecomment-1279980134

**Comment by jneilliii** [comment]
@OllisGit any input?

**Comment by jneilliii** [comment]
I've closed this abandonment request, but don't see a comment from you @OllisGit on the linked ticket...
