### ISSUE TITLE
[Listing Error] Filament Sensor Reloaded

### ISSUE THREAD

**Issue by robbrad** [OctoPrint/plugins.octoprint.org#1154]
### Which Plugin?

https://plugins.octoprint.org/plugins/filament_sensor_reloaded/

### What kind of listing error are you reporting?

Version mismatch

### What specifically is broken or wrong?

page says 

Compatibility Information

        OctoPrint: 1.2.6+
        Operating Systems: Linux, FreeBSD
        Python: >=2.7,<3

yet
https://github.com/nickmitchko/Octoprint-Filament-Reloaded/blob/master/octoprint_filamentreload/__init__.py#L298-L300

**Comment by jneilliii** [comment]
Also, there is a PR that is just waiting to be merged that will fix the error. You can install with the following URL in Plugin Manager > Get More > ...from URL.

```
https://github.com/grk3010/Octoprint-Filament-Reloaded/archive/refs/heads/grk3010.zip
```

@nickmitchko any chance we can get that PR merged?
