### ISSUE TITLE
[Listing Error] Ikea Tradfri

### ISSUE THREAD

**Issue by Martin17017** [OctoPrint/plugins.octoprint.org#1160]
### Which Plugin?

plugins.octoprint.org/plugins/ikea_tradfri/

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

Can't install plugin

**Comment by jneilliii** [comment]
As you didn't include any details relative to the typo, I assume you are just having install issues. Please report bugs with the plugin on its GitHub repository.
