### ISSUE TITLE
Installiere Plugin "PSU Control - FRITZ!Box" von https://github.com/not-na/OctoPrint-PSUControl-Fritz/archive/master.zip... /usr/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpna0_16zf/OctoPrint-PSUControl-Fritz-master.zip --no-cache-dir Processing /tmp/tmpna0_16zf/OctoPrint-PSUControl-Fritz-master.zip Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'done' Collecting simpletr64@ git+https://github.com/tobyp/simpletr64.git Cloning https://github.com/tobyp/simpletr64.git to /tmp/pip-install-vu_pzrfg/simpletr64_b96bc84eb25342eca1a7bebc4a15d7bc ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH? Fehler! Could not parse output from pip, see plugin_pluginmanager_console.log for generated output[Listing Error] PSU Control - FRITZ!Box

### ISSUE THREAD

**Issue by byFops** [OctoPrint/plugins.octoprint.org#1162]
### Which Plugin?

https://github.com/Tomatenjoghurt/OctoPrint-PSUControl-openHAB3

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

Installiere Plugin "PSU Control - FRITZ!Box" von https://github.com/not-na/OctoPrint-PSUControl-Fritz/archive/master.zip...
/usr/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmpna0_16zf/OctoPrint-PSUControl-Fritz-master.zip --no-cache-dir
Processing /tmp/tmpna0_16zf/OctoPrint-PSUControl-Fritz-master.zip
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting simpletr64@ git+https://github.com/tobyp/simpletr64.git
Cloning https://github.com/tobyp/simpletr64.git to /tmp/pip-install-vu_pzrfg/simpletr64_b96bc84eb25342eca1a7bebc4a15d7bc
ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jneilliii** [comment]
The error seems to be because your system doesn't have git installed. 'sudo apt install git` should fix it, but it's not a bug in plugin repository listing.
