### ISSUE TITLE
Login button on webpage unresponsive

### ISSUE THREAD

**Issue by iceblu008** [OctoPrint/plugins.octoprint.org#120]
When you try to run this plugin with octoprint 1.3.5 it makes the login button not work and renders octoprint useless

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
