### ISSUE TITLE
[Listing Error] Slicer Thumbnails

### ISSUE THREAD

**Issue by ghost** [OctoPrint/plugins.octoprint.org#1202]
### Which Plugin?

https://plugins.octoprint.org/plugins/prusaslicerthumbnails/

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

<img width="292" alt="Screen Shot 2023-06-14 at 09 14 11" src="https://github.com/OctoPrint/plugins.octoprint.org/assets/79003022/c52343e7-9581-4687-bd7e-10c2a4a194be">

 Attached screen shot of missing thumbnails have checked Prusa and activated there, do you know of any conflicts with other plugins on Octoprint

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)

**Comment by ghost** [comment]
Apologies. when looking into this issue and setting up on its help page. the report a problem was to the right and i thought it was for the plugin concerned. sorry to waste your time
