### ISSUE TITLE
[Listing Error] OctoLight Home Assistant

### ISSUE THREAD

**Issue by hansvanlin** [OctoPrint/plugins.octoprint.org#1208]
### Which Plugin?

https://plugins.octoprint.org/plugins/octolightHA/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

link to installer is broken. 
![image](https://github.com/OctoPrint/plugins.octoprint.org/assets/108009649/e847feda-396a-4b6c-b346-d2371b4b2c7b)

**Comment by jneilliii** [comment]
@mark-bloom looks like you need to fix your install URL. Also, please enable issues on your plugin repo. 

EDIT: most people just use the download zip url `https://github.com/mark-bloom/OctoLight_Home-Assistant/archive/master.zip`

**Comment by mark-bloom** [comment]
Issues have been enabled on the plugin repo and a pull request has been opened for the corrected download link in the .md file.

Thank you again for the commentary.

**Comment by jneilliii** [comment]
Pull request merged, should resolve issue once pushed to the site shortly.
