### ISSUE TITLE
[Listing Error] OctoLight Home Assistant

### ISSUE THREAD

**Issue by JottyTheHero** [OctoPrint/plugins.octoprint.org#1210]
### Which Plugin?

https://github.com/mark-bloom/OctoLight_Home-Assistant

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

If you use the plugin manager of OctoPrint, the archive can not be found.

**Comment by foosel** [comment]
Duplicate of #1208 and since fixed by a PR. Current plugin repo json contains the fixed link, so please reload from the repository if you are still seeing the old one.
