### ISSUE TITLE
[Listing Error] OctoLight Home Assistant

### ISSUE THREAD

**Issue by benjaminbrandt** [OctoPrint/plugins.octoprint.org#1211]
### Which Plugin?

https://plugins.octoprint.org/plugins/octolightHA/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

Install error for all three options (from within octoprint, via url, via zip).

Could not fetch plugin from server, got 404 Client Error: Not Found for url: https://github.com/mark-bloom/OctoLight_Home-Assistant/releases/download/release/OctoLight-master.zip

**Comment by jneilliii** [comment]
duplicate, this has been fixed but you may need to force a software update check within OctoPrint as it seems you're trying to install from a cached URL that has been changed.
