### ISSUE TITLE
[Abandoned Plugin] Filament Manager

### ISSUE THREAD

**Issue by wizardkitty** [OctoPrint/plugins.octoprint.org#1212]
### Which Plugin?

https://plugins.octoprint.org/plugins/filamentmanager/

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/OllisGit/OctoPrint-FilamentManager/issues/120

**Comment by wizardkitty** [comment]
The plugin has sat abandoned for some time and issues are starting to creep in. It no longer installs or functions on some machines.

**Comment by jneilliii** [comment]
@OllisGit are you done with plugin development?

**Comment by jneilliii** [comment]
per https://github.com/OctoPrint/plugins.octoprint.org/issues/1213#issuecomment-1647442098 @OllisGit is still around for maintaining plugin, was just on break.
