### ISSUE TITLE
[Abandoned Plugin] OctoLight

### ISSUE THREAD

**Issue by dragoslavvb** [OctoPrint/plugins.octoprint.org#1225]
### Which Plugin?

https://plugins.octoprint.org/plugins/octolight/

### Link to ticket on plugin's issue tracker confirming abandonment

https://github.com/gigibu5/OctoLight/issues/35

**Comment by jneilliii** [comment]
I've posted the above abandonment request for you on the original repo. If they do not respond with 14 days we can proceed with marking the plugin as abandoned.

**Comment by jneilliii** [comment]
@thomst08 has shown interest in adoption in above linked comment.
