### ISSUE TITLE
[Listing Error] OctoPrint-OctoVox

### ISSUE THREAD

**Issue by Hoschie0815** [OctoPrint/plugins.octoprint.org#1243]
### Which Plugin?

https://github.com/johnnyruz/OctoPrint-OctoVox/archive/master.zip

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

Hi, I tried to install the Octovox-Plugin. The installation-process interrupted. I got this message:

Installiere Plugin von https://github.com/johnnyruz/OctoPrint-OctoVox/archive/master.zip...
/home/pi/oprint/bin/python -m pip --disable-pip-version-check install file:///tmp/tmpxfz9puxt/OctoPrint-OctoVox-master.zip --no-cache-dir pip install "https://github.com/johnnyruz/OctoPrint-OctoVox/archive/master.zip"
ERROR: Invalid requirement: 'pip install "https://github.com/johnnyruz/OctoPrint-OctoVox/archive/master.zip"'
Hint: It looks like a path. File 'pip install "https://github.com/johnnyruz/OctoPrint-OctoVox/archive/master.zip"' does not exist.
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

I started the installation in OctoPrint, Settings, PluginManager, more, from URL.
I allready used Microsoft Edge, Firefox and Google Chrome...
What can I do to fix the problem?

Kind regards, Jörg

**Comment by jneilliii** [comment]
Unable to reproduce this issue, I just installed without error. I suggest opening an issue on the plugin's repository or possibly reach out on the Discord server in the support-plugin channel with the file `plugin_pluginmanager_console.log` from OctoPrint's logging section. 

![image](https://github.com/OctoPrint/plugins.octoprint.org/assets/5249455/721845d0-da15-4974-94f6-84afd52bdec3)
