### ISSUE TITLE
[Listing Error] Filament Sensor Reloaded

### ISSUE THREAD

**Issue by Greimelinio09** [OctoPrint/plugins.octoprint.org#1280]
### Which Plugin?

https://plugins.octoprint.org/plugins/filament_sensor_reloaded/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

I don't get the signal that there is filament in the sensor

**Comment by cp2004** [comment]
You have reported a "broken link on the listing". If there is a broken link, you should specify. Please don't use this to ask for help using the plugin.
