### ISSUE TITLE
OctoRelay

### ISSUE THREAD

**Issue by ea4eng** [OctoPrint/plugins.octoprint.org#1289]
### Which Plugin?

https://github.com/borisbu/OctoRelay

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

Once this plugin is installed, nothing is displayed in the navigation bar.
My system is completely updated.

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
