### ISSUE TITLE
[Listing Error] Print History

### ISSUE THREAD

**Issue by COstrom7219** [OctoPrint/plugins.octoprint.org#1292]
### Which Plugin?

https://github.com/imrahil/OctoPrint-PrintHistory/archive/master.zip

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

I try to install but it just says "Error!
Could not install plugin, unknown error, please consult octoprint.log for details"

**Comment by jneilliii** [comment]
This must be a local network issue or problem with GitHub when you were attempting, I'm able to install without error. This issue tracker is reserved for problems related to the plugin listings themselves, for issues with the plugin directly please open issue on it's issue tracker.
