### ISSUE TITLE
[Listing Error] OctoPrint-Hologram

### ISSUE THREAD

**Issue by waldentj** [OctoPrint/plugins.octoprint.org#1297]
### Which Plugin?

https://plugins.octoprint.org/plugins/hologram/?utm_source=octoprint&utm_medium=announcements&utm_content=1.10.0

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

pluging wont install and fails. also fails install when manually running the install command.

**Comment by jneilliii** [comment]
I see no issues with any of the links. Please report issues with the plugin itself on the plugin's repo. 

There appears to already be an issue [here](https://github.com/MarkSlat/OctoPrint-Hologram/issues/1) ]for this, maybe check that out and provide more details.
