### ISSUE TITLE
[Listing Error] OctoPrint-GitFiles

### ISSUE THREAD

**Issue by jacopotediosi** [OctoPrint/plugins.octoprint.org#1328]
### Which Plugin?

https://plugins.octoprint.org/plugins/gitfiles/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

Both homepage and source are 404

**Comment by jacopotediosi** [comment]
@OutsourcedGuru idk if you can take a look

**Comment by jneilliii** [comment]
I will be marking this one as abandoned. OutsourceGuru has been gone for some time. I did find this fork of his repo though on github.

https://github.com/itnachos/OctoPrint-GitFiles

**Comment by jneilliii** [comment]
There are also other forks that have had updates to them since they were split. I know @tidelineio was actively developing the plugin to work for his workflow. 

https://github.com/tidelineio/OctoPrint-GitFiles

**Comment by jneilliii** [comment]
plugin listing removed since it has been taken down from GitHub by original author.
