### ISSUE TITLE
[Listing Error] OctoPrint-SkipTo

### ISSUE THREAD

**Issue by gconceicao** [OctoPrint/plugins.octoprint.org#1333]
### Which Plugin?

https://github.com/awe-source/OctoPrint-SkipTo

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

In my octoprint dind't work, when I set the z height, and send it to the print, just do nothing

**Comment by jneilliii** [comment]
Please open issue with the plugin in its GitHub repo, this issue tracker is reserved for the official plugin repo listings only.
