### ISSUE TITLE
indication of heating timer

### ISSUE THREAD

**Issue by cnlson** [OctoPrint/plugins.octoprint.org#136]
i'd like some sort of notification that the heat timer is beginning. for instance maybe move the print head up 10 mm and back down 9mm every 60 seconds.

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
