### ISSUE TITLE
404 Error on "More..." link

### ISSUE THREAD

**Issue by MikeZets** [OctoPrint/plugins.octoprint.org#146]
On page    http://octoprint.github.io/plugins.octoprint.org/
the "More..." link goes to a missing page and displays a 404 error message.

**Comment by MikeZets** [comment]
Sorry.  I couldn't navigate my way back to the referring URL.  I was in the
Facebook Users Group Photos section and found the link to Plug-ins.  Went
there and then got the 404 when I tried to click on "More..."

*Mike Zets*
8346 Ledgestone Avenue
Sylvania, OH  43560
*412 670-7646 (*Cell)
MikeZets@gmail.com
*www.MikeZets.info <http://www.mikezets.info/>*

**Comment by foosel** [comment]
Sounds like someone linked to the public github pages endpoint instead of the actual domain. No wonder that that made things hiccup. I'll see if I can't add some kind of JS redirect...
