### ISSUE TITLE
OctoPrint-CustomBackground did not work after installing OctoPrint-Tempsgraph plugin

### ISSUE THREAD

**Issue by JLatasa** [OctoPrint/plugins.octoprint.org#155]
OctoPrint-CustomBackground did not work after installing OctoPrint-Tempsgraph plugin.

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
