### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by 3d-Printers** [OctoPrint/plugins.octoprint.org#160]
octoprint tab order keeps give a error durring install

Something went wrong
Installing the plugin from "https://github.com/jneilliii/OctoPrint-TabOrder/archive/master.zip" failed: Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by kantlivelong** [comment]
This tracker is reserved for:

missing or broken homepage, source or download URLs
broken images
incorrect compatibility information
... in short, anything related to the data on plugins.octoprint.org
If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
