### ISSUE TITLE
Plugin PolarCloud doesn't work inside Octoprint 1.3.8?

### ISSUE THREAD

**Issue by komo68** [OctoPrint/plugins.octoprint.org#192]
Hi,
today I installed Octoprint version 1.3.8 and then the plugin PolarCloud. After installing it does not appear in the plugin's menu?
![pola_plugin](https://user-images.githubusercontent.com/12023583/39598871-4bf10c04-4f1a-11e8-81a9-107595904fc1.jpg)

Best regards,

Viljem

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
