### ISSUE TITLE
Heatertimeout 

### ISSUE THREAD

**Issue by jackblacke** [OctoPrint/plugins.octoprint.org#198]
i download Heatertimeout plugin to my OctoPrint with my printer Prusa MK3 ..
when its activated the printer cooling down and the hotend nover heat again 
i got this massage on OctoPrint
 " Error reported by printer
Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting) "
iam not good in code so please if any one know how i fix this ... pleasse help me ..
thank you ..

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
