### ISSUE TITLE
PolarCloud doesn't install correctly under Octoprint 0.15

### ISSUE THREAD

**Issue by komo68** [OctoPrint/plugins.octoprint.org#200]
Hello,

The PolarCloud is very usefull tool under Octoprint, but with it doesn't work with new RPI 3 B+ and Octoprint version 0.15. After installation it can't be visible in Octoprint plugin menu?

Thank You,
Best regards,

Viljem

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
