### ISSUE TITLE
octoprint on raspberry pi

### ISSUE THREAD

**Issue by Johnrasp** [OctoPrint/plugins.octoprint.org#241]
I'm not sure if this plugin is compatible with pi.
Following your pip install on raspberry pi 3 this error occurs:-

sudo pip install "https://github.com/gfk76/OctoPrint-Nexmonotifier/archive/master.zip"
Collecting https://github.com/gfk76/OctoPrint-Nexmonotifier/archive/master.zip
  Downloading https://github.com/gfk76/OctoPrint-Nexmonotifier/archive/master.zip
     \ 552kB 19.5MB/s
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-jBvou9-build/

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
