### ISSUE TITLE
Unable to control or live view

### ISSUE THREAD

**Issue by cappy175** [OctoPrint/plugins.octoprint.org#242]
I am unable to control or live view. I have to take a picture to see the printer. Also, the over the cloud controls states that I have to be on the same network to use the control function. I would like to remotely stop a print if I see a problem. 

READ FIRST, THEN DELETE:

What kinds of issues you should report here:

  * missing or broken homepage, source or download URLs
  * broken images
  * incorrect compatibility information
  * ... in short, anything related to the data on plugins.octoprint.org

What you should not report here:

  * Any kinds of issues with the plugins themselves - report those
    to the plugin author instead!

Thanks :)

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
