### ISSUE TITLE
Youtube Live didn´t work on my Octopi.

### ISSUE THREAD

**Issue by alebote1043** [OctoPrint/plugins.octoprint.org#255]
I can not get this plugin to work, it always shows the same error. Everything is well configured and I have tried several octoprint installations.
The error:
YouTube Live Error
('Connection aborted.', error(2, 'No such file or directory'))

Thanks

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
