### ISSUE TITLE
[TODO]  - Fix deprecated gem used in Travis CI

### ISSUE THREAD

**Issue by kantlivelong** [OctoPrint/plugins.octoprint.org#258]
Noticed the following warning when reviewing a recent build failure:

$ bundle exec jsonlint ./_site/plugins.json  

[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.  

The command "bundle exec jsonlint ./_site/search.json" exited with 0.

**Comment by foosel** [comment]
Not exactly sure if there's anything *we* can fix here... I just checked and `optimist` is a [command line option parser](https://rubygems.org/gems/optimist). My guess is either `bundler` or `jsonlint` depend on whatever this was called before.

**Comment by kantlivelong** [comment]
This may no longer be relevant with the recent build changes. @foosel

**Comment by foosel** [comment]
We are still using travis for the link testing and such, need to switch that over to actions too though. Same workflow should do.

**Comment by foosel** [comment]
Now we no longer use travis.
