### ISSUE TITLE
needs better walkthrough and install scripts

### ISSUE THREAD

**Issue by SirBastol** [OctoPrint/plugins.octoprint.org#264]
needs : 1. better walks through with current screenshots and steps with regard to where to find on youtube teh info to paste with and example of that they look like ( for noobs and pros who dont mess with youtube much)
2. ability to specify a sound track  or no sound.. 
3. explanation of steps for public url for streaming ( does youtube need it or is it jsut for testing)
4. install scripts should be more automagic.. less manual intervention for setup -- ie step by step ask questions and fillthe blanks for you ( from teh octoprint plugin config page.. if ti cant find what it needs you should be given the option to install it  instead of jsut not workign and stating an irrelevant error.

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
