### ISSUE TITLE
Broken link in Growl plugin; build failed.

### ISSUE THREAD

**Issue by tjjfvi** [OctoPrint/plugins.octoprint.org#268]
The Travis CI build failed in PR #267, but I looked at the error and it seems to be a broken link in the Growl plugin.

**Comment by kantlivelong** [comment]
Looks like it's [no longer maintained](https://github.com/OctoPrint/OctoPrint-Growl/issues/7). Might be time for removal.

Tagging in @foosel

**Comment by foosel** [comment]
Would feel bad a bit about removing the plugin completely considering that it still works (and maybe it'll still find an adopter? hope dies last...) and only a link in its listing here was broken. I removed that link in 20358947222380264124b081ddd9bb9b590530d2 instead.

Thanks for the heads-up @tjjfvi!
