### ISSUE TITLE
Bedleveling

### ISSUE THREAD

**Issue by chrisboer** [OctoPrint/plugins.octoprint.org#270]
BedLevelVisualizer plugin stops installation

Installing plugin "Bed Level Visualizer" from https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Running setup.py install for numpy: still running...Error!Could not install plugin, unknown error, please consult octoprint.log for details

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
