### ISSUE TITLE
OctoPrint-WebcamStreamer

### ISSUE THREAD

**Issue by darkstudio** [OctoPrint/plugins.octoprint.org#276]
WebcamStreamer Error
'NoneType' object has no attribute 'containers'

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
