### ISSUE TITLE
Spelling error on PrintTrack plugin

### ISSUE THREAD

**Issue by CAP1Sup** [OctoPrint/plugins.octoprint.org#285]
I noticed a small spelling error while reading up on [this plugin](https://plugins.octoprint.org/plugins/printtrack/?utm_medium=announcements&utm_source=octoprint&utm_content=1.3.10 ).

The original sentence is "There are custimization options to change how it is displayed and also has adjustable strings so you can translate them or just make them something else."

The sentence should say "There are customization options to change how it is displayed and also has adjustable strings so you can translate them or just make them something else."

Thanks,
CAP1Sup

**Comment by foosel** [comment]
Should be fixed.
