### ISSUE TITLE
Display ETA

### ISSUE THREAD

**Issue by Loeikie** [OctoPrint/plugins.octoprint.org#288]
I love Display ETA i had to re-install Octoprint. Since new institutions ETA freezes new print at the start

Printing never starts. If I disable ETA and reboot the print works fine

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
