### ISSUE TITLE
ESPurnaRGB not setting colors?

### ISSUE THREAD

**Issue by jacobwtyler** [OctoPrint/plugins.octoprint.org#300]
I just got a Magichome LED Controller and flashed it with ESPurna and I can control all the colors through the web interface just fine.  I installed the plugin through Octoprint and the M150 command turns off the light just like it should but no matter what color I put in, it always turns it on to whatever color I have set in the web interface.  Any ideas? I'm entering:
M150 R255
or 
M150 R U B
or 
M150 R255 U127
just as it reads in the instructions.  Thank you for any help.

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
