### ISSUE TITLE
LEDStripControl - ERROR - Unable to communicate with PiGPIOd

### ISSUE THREAD

**Issue by Supersizeme2007** [OctoPrint/plugins.octoprint.org#311]
After update octoprint to 1.3.11

LEDStripControl - ERROR - Unable to communicate with PiGPIOd in LOG-File.

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint

**Comment by Supersizeme2007** [comment]
Hi
It is only the Plugin LEDStripControl. 
If i deaktivate it all normal!



Gesendet von Mail für Windows 10

Von: Shawn Bruce
Gesendet: Dienstag, 14. Mai 2019 23:52
An: OctoPrint/plugins.octoprint.org
Cc: Supersizeme2007; Author
Betreff: Re: [OctoPrint/plugins.octoprint.org] LEDStripControl - ERROR -Unable to communicate with PiGPIOd (#311)

This tracker is reserved for:
• missing or broken homepage, source or download URLs
broken images
• incorrect compatibility information
• ... in short, anything related to the data on plugins.octoprint.org
If this issue only applies to a specific plugin please report to the appropriate plugin repository.
If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
