### ISSUE TITLE
Support request for Lerdge-Boards

### ISSUE THREAD

**Issue by ThomasS463** [OctoPrint/plugins.octoprint.org#319]
Hello!

My new board is a Lerdge K. It uses a little bit different Output schematics:
Recv: (0,0,0.064)  (1,0,-0.014)  (2,0,-0.023)  (3,0,-0.130)  (4,0,-0.006)
Recv: (4,1,-0.087)  (3,1,-0.107)  (2,1,-0.037)  (1,1,0.019)  (0,1,0.078)
Recv: (0,2,0.134)  (1,2,0.036)  (2,2,-0.007)  (3,2,-0.050)  (4,2,-0.044)
Recv: (4,3,0.022)  (3,3,-0.014)  (2,3,0.048)  (1,3,0.097)  (0,3,0.178)
Recv: (0,4,0.176)  (1,4,0.109)  (2,4,0.066)  (3,4,0.029)  (4,4,0.038)

Could it be made to support this style of Output too?

Thanks & greetings, Thomas

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for issues with the *plugin repository*. Thank you! :)
