### ISSUE TITLE
TouchUI stops working when Shutdown Printer Plugin is active

### ISSUE THREAD

**Issue by ARCH-3D** [OctoPrint/plugins.octoprint.org#320]
Hello,
After installing the last upgrade the TouchUI stops workinkg. And the problem is with Shutdown Printer plugin. When the ShutDown Printer plugin is active the TouchUI stops working and when is disabled the TouchUI works properly. I would like to know if you could solve this incompatibility. Many thanks.
Best regards,

**Comment by BillyBlaze** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint

For other affected follow this thread: https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/302
