### ISSUE TITLE
Site not updated

### ISSUE THREAD

**Issue by rlogiacco** [OctoPrint/plugins.octoprint.org#323]
I was waiting to proudly share the publication of my first plugin for Octoprint, but for some reason the pages don't seem to have been updated even if the pull request has been merged a few days ago.

it looks like last successful update occurred on May 12.

**Comment by foosel** [comment]
Yeah, @gdombiak also pinged me about a similar issue. Github Pages sometimes needs a bit of extra convincing. I'll look into this right away.

**Comment by foosel** [comment]
Seems to have been fixed by a friendly poke via a small commit. Some day I might even understand why this sometimes happens....

**Comment by rlogiacco** [comment]
Thank you a million!
