### ISSUE TITLE
S20 no longer available

### ISSUE THREAD

**Issue by 3dprinting-noob** [OctoPrint/plugins.octoprint.org#356]
this is a great plugin, however s20 sockets are not available for purchase,
Can you please update this plugin for Orvibo s25 socket as well please

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
