### ISSUE TITLE
OctoPrint-PCA9685LEDStripControl not visible after successful installation

### ISSUE THREAD

**Issue by agarthand** [OctoPrint/plugins.octoprint.org#367]
I'm trying to get the OctoPrint-PCA9685LEDStripControl plugin working. The PCA9685 board itself is cabled and detected by the Raspi. The installation of the plugin - either through plugin manager or pip - is also working without any reported issue.

But (even after a reboot) the plugin is not listed as installed - still available in the plugin manager to be installed - nor do I find any options to have it configured.

Even tried to uninstall the plugin (using pip uninstall) and start over from beginning, no change.

Hope I'm just missing something easy or somebody is able to guide me where to look into. First time that I'm struggeling with an plugin. Looking forward for some help...

Used versions:
OctoPrint version : 1.3.12
OctoPi version    : 0.16.0
on a Raspi 3B+

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
