### ISSUE TITLE
Does not work on raspberry pi 4

### ISSUE THREAD

**Issue by FloBau3D** [OctoPrint/plugins.octoprint.org#369]
Hello,

I tried to download Tuya Smart Plug on octoprint but it gives me an error message. On my raspberry pi 3b + it works nickel but not on the raspberrypi 4B ducoup I think it comes from that.

Florian BAUDRY

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
