### ISSUE TITLE
ne fonctionne pas sur octoprint

### ISSUE THREAD

**Issue by didierchastanet** [OctoPrint/plugins.octoprint.org#375]
https://github.com/ziirish/OctoPrint-TuyaSmartplug/archive/master.zip
Installation du plugin depuis l'archive importée...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install /tmp/tmpXCjJh4.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpXCjJh4.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-TuyaSmartplug==0.2.2) (1.3.12)
Collecting pyaes==1.6.1
Downloading https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz
Collecting pytuya==7.0.5
Downloading https://files.pythonhosted.org/packages/4a/69/b20175759e97294f694939ab9bc4be378b3c60ef2d1601d80fc3cc6d2daa/pytuya-7.0.5.zip
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qcKM5l/pytuya/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qcKM5l/pytuya/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qcKM5l/pytuya/pip-egg-info
cwd: /tmp/pip-install-qcKM5l/pytuya/
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-qcKM5l/pytuya/setup.py", line 9, in <module>
import pytuya
File "pytuya/__init__.py", line 28, in <module>
import pyaes  # https://github.com/ricmoo/pyaes
ImportError: No module named pyaes
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by foosel** [comment]
I do not speak French, but this seems to be about an issue with a specific plugin.

Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
