### ISSUE TITLE
There was an error with the template index.jinja2

### ISSUE THREAD

**Issue by RezKom** [OctoPrint/plugins.octoprint.org#378]
There was an error with the template index.jinja2 at line number 106: 'ascii' codec can't decode byte 0xd4 in position 0: ordinal not in range(128)

**Comment by foosel** [comment]
That's a) not enough information to even begin to figure out what went wrong, b) it's completely unclear on whether that error message arouse in a plugin or in OctoPrint core or whatever and c) this is the wrong tracker for bugs of any kind anyhow.
