### ISSUE TITLE
Unable to install Printer Statistics

### ISSUE THREAD

**Issue by sebrob7** [OctoPrint/plugins.octoprint.org#399]
Hi,

I'm unable to install the plugin.  Here's what it give's me :

"Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output"

Can you help me figure out a solution to install it?  I use a Raspberry Pi 3B+.  Thank you.

It also gives this at the end of the processus : "RuntimeError: Python version >= 3.5 required.".

Seb

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
