### ISSUE TITLE
Settings View Brokem

### ISSUE THREAD

**Issue by thecoolwinter** [OctoPrint/plugins.octoprint.org#400]
When the plugin is installed the settings screen's menu button doesn't work. It looks like it's trying to collapse the side menu in settings, but it's just getting rid of it completely.

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
