### ISSUE TITLE
Xiaofang hack like webcam possible?

### ISSUE THREAD

**Issue by Heracles44** [OctoPrint/plugins.octoprint.org#401]
Hi,

Can we use Xiaofang hack with RTSP MJPEG like a webcam?
I add it in my Jeedom and i try to use the RTSP MJPEG in Octoprint but i don't know why.
I have login and password in my Xiaofang camera.

Thank you for your help

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
