### ISSUE TITLE
Dont see progress title

### ISSUE THREAD

**Issue by DOC1973** [OctoPrint/plugins.octoprint.org#402]
Hi,

  * missing progress title on site

I have installed and no errors but after restart or printing I dont see nothing.

Thanks :)

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
