### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Neiljclements** [OctoPrint/plugins.octoprint.org#413]
I have an issue installing.  It sits at the screen shown in the picture and does no more. I've tried two of my OctoPrint servers and they both did the same.

![Capture](https://user-images.githubusercontent.com/7466466/77549117-5bfb2180-6ea7-11ea-9de0-2d75e33265bf.PNG)

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)

**Comment by Neiljclements** [comment]
Apologies
