### ISSUE TITLE
[Listing Error] AstroPrint Cloud

### ISSUE THREAD

**Issue by maramauphoto** [OctoPrint/plugins.octoprint.org#443]
**Which Plugin? (URL to plugin page on plugin repository)**
https://github.com/AstroPrint/OctoPrint-AstroPrint/releases/tag/1.5.3
**What's wrong with the plugin *listing*?**
broken links 
500 internal server error

**Comment by foosel** [comment]
https://plugins.octoprint.org/plugins/astroprint/ is working great over here. If you are currently running into internal server errors anywhere on plugins.octoprint.org or github, it's due to Github having a bit of an outage from the looks of it.
