### ISSUE TITLE
[Listing Error] Plabric

### ISSUE THREAD

**Issue by fblondeau** [OctoPrint/plugins.octoprint.org#460]
**Which Plugin? (URL to plugin page on plugin repository)**
Plabric

**What's wrong with the plugin *listing*?**

No where its written that you need to have an android phone. The IOS version is not available yet therefor making the plugging useless. 

A note should be displayed that IOS user can't use it until they release their IOS app. ETA?

**Comment by foosel** [comment]
Added a note to the listing.

@plabric See the complaint and commit above, I've modified your listing to indicate that the app is currently only available for Android with iOS coming. Please send a listing update PR once the iOS app is available.
