### ISSUE TITLE
[Abandoned Plugin] FilamentManager

### ISSUE THREAD

**Issue by DotNetRob** [OctoPrint/plugins.octoprint.org#471]
**Which Plugin? (URL to plugin page on plugin repository)**
https://plugins.octoprint.org/plugins/filamentmanager/

**Ticket on plugin's issue tracker confirming abandonment:** Post the question if it was still being maintained approximately a week ago, no response from owner.   
https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/210

**Is there someone open to adopting it? ("no" or @-mention user):**

**Comment by foosel** [comment]
Please give it two weeks (so one more week - life happens, Github can't take priority for everyone out there) and then ping me here again. If no reaction has happened then we can mark it as abandoned.

**Comment by DotNetRob** [comment]
> Please give it two weeks (so one more week - life happens, Github can't take priority for everyone out there) and then ping me here again. If no reaction has happened then we can mark it as abandoned.

Has officially been 2 weeks since my abandonment post.

**Comment by FixxCZ** [comment]
This is one of a kind plugin, it would be really nice if someone could take the ownership and keep it running. Thanks in advance.

**Comment by I-like-stuff** [comment]
If no one picks this up then I found this by OllisGit who also make display layer progress and others, he said in a recent discussion that he would begin working on this after the print history plugin which seems almost finished with for it’s first version so we will just have to wait.

https://github.com/OllisGit/OctoPrint-SpoolManager

**Comment by Zouljiin** [comment]
it should really be merged with 
https://github.com/OllisGit/OctoPrint-PrintJobHistory
it has great stuff and records filament usage but lacks the exact features that filamentmanager has

**Comment by attacktwinkie** [comment]
I'll look into picking this up....  give me couple days to review whats here.   Ive wanted to fork this for some time and I migjt just pick this one up from here.

**Comment by Kawuezel** [comment]
@attacktwinkie 
I would really like that someone is taking over the Filament Manager Plugin. I'm using it in addition to my OctoDash.

**Comment by RobeeeJay** [comment]
@attacktwinkie it would be so wonderful if you could pick this up! It's broken with the new OctoPrint 1.4.1rc1. 😞

I should really learn Python one day...

**Comment by cwbullet** [comment]
There might be another party interested.  My son got this working on my printers and it works with the single shared database.  Does anyone know if @attacktwinkie is planning on taking it over?

**Comment by jrummy333** [comment]
who has taken this over? I would really like to add a notes section for this plugin.  Do I have to take it over just to add this or how exactly do abandon GitHub function?

**Comment by OllisGit** [comment]
Hi everybody,
short advertisement: The first release candidate of the Spool Manager Plugin is out:
https://github.com/OllisGit/OctoPrint-SpoolManager

The plugin also include a note-section.

Some feature are missing for V1 (e.g. CSV Import/Export), but you can start testing and get a feeling how the plugin works. If you found an issue or have a feature request, please use the issue tracker of the repository.

BR
Olli

**Comment by RobeeeJay** [comment]
This looks very nice! I would love to use it, but not being able to import my existing FilamentManager data is blocking me. I have 38 spools I'm tracking and that's a lot to manually enter all over again. 😔

**Comment by OllisGit** [comment]
@RobeeeJay fyi: Its on my list for the final V1.0

**Comment by OllisGit** [comment]
Hi @RobeeeJay ,
the export of the FilamentManager-Database and an CSV-Import is now implemented in RC4.
https://github.com/OllisGit/OctoPrint-SpoolManager/releases/tag/1.0.0rc4

**Comment by RobeeeJay** [comment]
Thank you I will try this right now!!

**Comment by buffedelic** [comment]
this is a working fork. can confirm it is runing on 1.4.0 with python 3.7

**Comment by RobeeeJay** [comment]
Thank you @buffedelic! This seems to work fine and will let me upgrade Octoprint until SpoolManager is ready.

**Comment by NotExpectedYet** [comment]
Is this still available to pick up?

**Comment by cwbullet** [comment]
If anyone picks this up, my son has also updated it.  He is in school and does not have the time.

**Comment by jneilliii** [comment]
Does @benjamin-salchow want to take over this plugin possibly? Also, @attacktwinkie mentioned it. No-one has said outright they want to take over @NotExpectedYet.

**Comment by foosel** [comment]
Yep, we need someone to shout a loud and clear "here, I'll do it!" before this can proceed in any direction.

**Comment by mrseeker** [comment]
Maybe @OllisGit is willing to give a shout out? It seems that his plugin does the same thing and more...

**Comment by jneilliii** [comment]
Except integrate with OctoFarm...

**Comment by NotExpectedYet** [comment]
> Except integrate with OctoFarm...

Wish I had the time. 

Id like to learn more about Python and its my interest to keep this plugin alive. 

I will happily maintain it and hopefully add to its feature set.

**Comment by jneilliii** [comment]
That's great @NotExpectedYet will just need you to create the repo and have all the releases ready. Preferably, with the Python 3 fix already applied, etc. Once that is up and ready we can begin the transition process.

**Comment by NotExpectedYet** [comment]
Sound i will get on it this weekend

**Comment by RobeeeJay** [comment]
I have already moved to using SpoolManager:
https://github.com/OllisGit/OctoPrint-SpoolManager

It's in the plugins repo, you can export directly from FilamentManager to SpoolManager from within the latter's UI, and it supports more options already, plus it's actively developed.

**Comment by cwbullet** [comment]
Charles knows how to find it.

**Comment by NotExpectedYet** [comment]
https://github.com/NotExpectedYet/OctoPrint-FilamentManager/ 

If anyone has any commits they want to merge here's the one I forked.

**Comment by OllisGit** [comment]
Unfortunately I was on summer vacation... well it was really nice.
But I missed the question, if I could pick up the Filament Manager-Plugin two days ago.
Yes, I can...maybe it is too late now.....@NotExcpectedYet or do you want to switch the responsibility to me?

**Comment by NotExpectedYet** [comment]
> Unfortunately I was on summer vacation... well it was really nice.
> But I missed the question, if I could pick up the Filament Manager-Plugin two days ago.
> Yes, I can...maybe it is too late now.....@NotExcpectedYet or do you want to switch the responsibility to me?

I havent gotten around to sorting it yet with Gina and Jin but your welcome to. Id only forked the one mentioned above with python3 support. 

Your in a better positlin to keep it running than i am as i was going to be learning Python to help grow its feature set. It is fine by me if you want to take it up, and massive thanks if you do!

**Comment by jneilliii** [comment]
Merged, just need to get the announcement made in OctoPrint for people to manually reinstall, @foosel?

**Comment by foosel** [comment]
> just need to get the announcement made in OctoPrint for people to manually reinstall, @foosel?

Should be live after 3849bf6938a7dea5c899ba29a74c6d7513f5abfe gets compiled. Side note: I need to build a better mechanism for this scenario right into OctoPrint, like an update config overlay that gets fetched from the repository... the notice mechanism was actually built rather for something like bugs in a specific version and thus needs individual versions, which for "anything before X" is a bit annoying. Needs to support version ranges too I guess.
