### ISSUE TITLE
Error Ultimaker Format Package

### ISSUE THREAD

**Issue by roverpete** [OctoPrint/plugins.octoprint.org#475]
<img width="417" alt="Screenshot 2020-05-12 at 11 10 00" src="https://user-images.githubusercontent.com/65222103/81672002-741c0580-9441-11ea-98f4-dcbd4cbd1e52.png">

Hi please can you help. I get this error when I install your format package remove it and cura works fine ? but it has put the file on the pi 
<img width="309" alt="Screenshot 2020-05-12 at 11 15 17" src="https://user-images.githubusercontent.com/65222103/81672366-f86e8880-9441-11ea-93a6-86dc5ff4b93d.png">

thanks

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
