### ISSUE TITLE
[Abandoned Plugin] Printer Statistics / OctoPrint-Stats

### ISSUE THREAD

**Issue by foosel** [OctoPrint/plugins.octoprint.org#479]
**Which Plugin? (URL to plugin page on plugin repository)**
https://plugins.octoprint.org/plugins/stats/

**Ticket on plugin's issue tracker confirming abandonment:**
https://github.com/amsbr/OctoPrint-Stats/issues/42 - no reply after 14 days.

**Is there someone open to adopting it? ("no" or @-mention user):**
no

**Comment by jmichelsen** [comment]
I'd be willing to take this up if people are still using it

**Comment by cp2004** [comment]
@jmichelsen - it looks like @AlexVerrico may already be looking at taking over maintenance of the plugin. You could try getting in contact to see if you can help out.

They posted an issue in that plugin's repo asking if he could take over it.
https://github.com/amsbr/OctoPrint-Stats/issues/48

**Comment by jmichelsen** [comment]
ah gotcha, thanks :)

**Comment by AlexVerrico** [comment]
@jmichelsen happy to discuss sharing ownership of the plugin, might be easier to chat through gitter though: https://gitter.im/AlexVerricoChat/octoprint-stats

**Comment by AlexVerrico** [comment]
G'Day all.
As I have been unable to make contact with the original maintainer, I have mirrored this repo to here: https://github.com/AlexVerrico/octoprint-stats
@jmichelsen If you want to help out with maintaining the plugin, please feel free to join the gitter chat for it https://gitter.im/AlexVerricoChat/octoprint-stats
As of now, there is no reason for listing in the plugin repo to be updated, but I will post an update here once that changes.
Cheers, Alex.

**Comment by AlexVerrico** [comment]
G'Day all.
I have submitted a PR to this repo to update the plugin repo.
As such, I believe we can close this issue.
Cheers, Alex.

**Comment by jneilliii** [comment]
I will keep this open for now until the merge is complete and all the notifications are created, etc.
