### ISSUE TITLE
[Feature Request] attach image at the end of a print

### ISSUE THREAD

**Issue by apphead** [OctoPrint/plugins.octoprint.org#525]
**What do you want to see implemented in the plugin repository?**
Take a picture at the end of each print and link it to the gcode. 

Basic features:  (see numbers in screenshot below)
- create a folder where the images linked to a printed item are stored. 
- If print was successful (completed) add a tick mark or in case of a cancelled print add a X stamp to the image.
- add button _view prints_ to the file & detail menus in the left column to view them. (1 in screenshot)
- settings: 
  - run gcode xyz before taking a picture in order to get a good and constant perspective / shot
  - image size
- delete images when gcode is deleted
- call the plugin _snatchprint_ :-)

Advanced features:
- cleanup of images: by date range, by folder, by individual item (in case you want to keep the gcode but not the images)
- select webcam 1 2 ... n
- buttons to browse through pictures (2-5 in screenshot)

![2020-06-13 08_04_32-0% -](https://user-images.githubusercontent.com/505490/84561468-f6535e80-ad4c-11ea-86df-0a49b54f21da.png)

**Why, what problems would be solved by this?**
Sometimes, I get back to a printed file long after the initial print and would like to see how it turned out back then. I partly achieve that by using the [Telegram Plugin](https://github.com/OctoPrint/plugins.octoprint.org/blob/01553518f433a85ad549b886d214b50a8bdf3853/_plugins/telegram.md) but my proposed feature would unite everything under the same umbrella. 
For the sake of documentation, that would be a handy feature. And storage space is hardly ever an issue anymore.

**Comment by jneilliii** [comment]
This is the wrong place for this request. This is for issues only related to the official plugin repo. For requests for new plugins ask on the community forum. 

Fur your reference, you may want to check out this already existing plugin, which I believe does most, if not all of what you're asking for. 

https://plugins.octoprint.org/plugins/PrintJobHistory/

https://plugins.octoprint.org/plugins/PrintJobHistory/
