### ISSUE TITLE
[Listing Error] OctoPrint-3DGeeks

### ISSUE THREAD

**Issue by fblondeau** [OctoPrint/plugins.octoprint.org#534]
***NOT OCTOPRINT PROBLEM***  

**Which Plugin? (URL to plugin page on plugin repository)**

OctoPrint-3DGeeks

**What's wrong with the plugin *listing*?**

Like to the main web site doesn't load in a modern Browser. Mix on a HTTP and HTTPS request and CDN issue. 

Does the mean the plugin is code like that? 

![Screen Shot 2020-06-23 at 12 07 57 AM](https://user-images.githubusercontent.com/11703371/85360148-5208af00-b4e6-11ea-968a-c4efe1f0abaa.png)

**Comment by jneilliii** [comment]
This is not an issue for the plugin repository, but more of an issue with the website the plugin is linking to. You should bring your concerns up withe the plugin author (linked below for your convenience) and not here.

https://github.com/2BWorks/OctoPrint-3DGeeks/issues
