### ISSUE TITLE
[Listing Error] GPX

### ISSUE THREAD

**Issue by boogiemann** [OctoPrint/plugins.octoprint.org#551]
**Which Plugin? (URL to plugin page on plugin repository)**

GPX

**What's wrong with the plugin *listing*?**

I have been using OctoPrint with GPX plugin with my WanHao Duplicator 4S for few years now. The SD card on my pi just died. I burned a new card with the latest OctoPi and installed the latest GPX plugin. It no longer connects to the printer. When I use /dev/tty/ACM0 at 115200, I get this following message in the State output.

Offline (Error: UnicodeDecodeError: ''ascii' codec can't decode byte 0x87 in position 1: ordinal not in range(128)' @ comm.py:_readline:2793)

Please help.

**Comment by jneilliii** [comment]
This is not the place to post for help with plugins, please open an issue on the plugin's repository directly or check on the community forum.
