### ISSUE TITLE
[Listing Error] OctoPrint-TuyaSmartplug

### ISSUE THREAD

**Issue by justin5188** [OctoPrint/plugins.octoprint.org#552]
https://github.com/ziirish/OctoPrint-TuyaSmartplug

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-DPtYRo/pytuya/

**Comment by jneilliii** [comment]
Appears you've already opened an issue on the plugin's repository, closing as the issue is with that plugin.
