### ISSUE TITLE
[Feature Request] Search by tags (As well as title, description, content)

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/plugins.octoprint.org#568]
**What do you want to see implemented in the plugin repository?**
Plugin search function searches by tags as well as what it searches now (Title, description content)

**Why, what problems would be solved by this?**
My latest plugin (Ws281x Led Status) can control ws2811 and ws2812 LEDs which are also known as Neopixels, which is the Adafruit name. I didn't put neopixel in the description, or all the different types of LED strip the plugin suppports. As a user, if I wanted to find a WS2811 plugin, I wouldn't put ws281x into the search bar necessarily, which is why I think it should support tag search

**Comment by foosel** [comment]
Closed by #577
