### ISSUE TITLE
[Listing Error] OctoPrint-TuyaSmartplug

### ISSUE THREAD

**Issue by 5Blue** [OctoPrint/plugins.octoprint.org#576]
**https://plugins.octoprint.org/plugins/tuyasmartplug/**

I'm trying to install this plugin but it give me this error

Installing plugin "OctoPrint-TuyaSmartplug" from https://github.com/ziirish/OctoPrint-TuyaSmartplug/archive/master.zip... /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpytysXW/OctoPrint-TuyaSmartplug-master.zip --no-cache-dir Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple Processing /tmp/tmpytysXW/OctoPrint-TuyaSmartplug-master.zip Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-TuyaSmartplug==0.2.3) (1.4.2) Collecting pyaes==1.6.1 Downloading https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz Collecting pytuya==7.0.6 Downloading https://files.pythonhosted.org/packages/35/82/a10d977c4a0879c37275e2793d983a8b7ac0f6738e937cdc159d4f3a15c1/pytuya-7.0.6.zip ERROR: Command errored out with exit status 1: command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-M1IKRW/pytuya/setup.py'"'"'; __file__='"'"'/tmp/pip-install-M1IKRW/pytuya/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-M1IKRW/pytuya/pip-egg-info cwd: /tmp/pip-install-M1IKRW/pytuya/ Complete output (7 lines): Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-M1IKRW/pytuya/setup.py", line 9, in <module> from pytuya.const import __author__, __version__ File "pytuya/__init__.py", line 28, in <module> import pyaes # https://github.com/ricmoo/pyaes ImportError: No module named pyaes ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. Error! Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jneilliii** [comment]
This issue tracker is for errors related to the plugin repo itself, not issues with the plugin themselves. Please check the plugin's issue tracker about this issue, linked below for your convenience. It appears there may already be an open ticket.

https://github.com/ziirish/OctoPrint-TuyaSmartplug/issues
