### ISSUE TITLE
[Abandoned Plugin] OctoPrint-CostEstimation

### ISSUE THREAD

**Issue by ikoutone** [OctoPrint/plugins.octoprint.org#623]
**Which Plugin? (URL to plugin page on plugin repository)**
https://github.com/malnvenshorn/OctoPrint-CostEstimation

**Ticket on plugin's issue tracker confirming abandonment:**
https://github.com/malnvenshorn/OctoPrint-CostEstimation/issues/29

**Is there someone open to adopting it? ("no" or @-mention user):**
No

**Comment by jneilliii** [comment]
@benjamin-salchow since you have a python 3 compatible fork, do you want to take over maintaining this plugin?

**Comment by RedCoder09** [comment]
OH NO!! I would take over, but I know nothing about coding so :/

**Comment by OllisGit** [comment]
Hi everybody,

I can take over the plugin responsibility.
I am just preparing the MR for the Plugin-Repo and also looking through the current open merge requests.

**Comment by jneilliii** [comment]
Pugin adopted, changes merged.
