### ISSUE TITLE
[Listing Error] OctoPrint-PrettyGCode

### ISSUE THREAD

**Issue by nebulla55** [OctoPrint/plugins.octoprint.org#627]
Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-req-build-ihxNJl/

**Which Plugin? (URL to plugin page on plugin repository)**

**What's wrong with the plugin *listing*?**

**Comment by jneilliii** [comment]
This appears to be a bug with the plugin, this tracker is for issue related to the plugin repo itself, please post your issue in that plugin's github repo.
