### ISSUE TITLE
[Does not work with Python 3.7.3] Bed Level Visualizer

### ISSUE THREAD

**Issue by MarshmallowBandito** [OctoPrint/plugins.octoprint.org#655]
**Which Plugin? (https://github.com/jneilliii/OctoPrint-BedLevelVisualizer)**

**What's wrong with the plugin *The plugin does not function in Octoprint instances running Python 3.7.3*?**

**Comment by cp2004** [comment]
The readme has a [known issue about this](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer#known-issues), and this is not the place to report bugs with the plugins.

**Comment by MarshmallowBandito** [comment]
Hi,

Sorry I just realised I needed to post this about another plugin. I managed to get this plugin working by using the readme.
I will close this thread.

Best regards
