### ISSUE TITLE
[Listing Error] Bed Level Visualizer

### ISSUE THREAD

**Issue by medoh300** [OctoPrint/plugins.octoprint.org#659]
**Bed Level Visualizer**

**it would be handy if the current description of the plugin shows that if you have python 3 , you need to do an extra step, took me 1 hour to figure it out , it is listed on the known issues of the plugin 🤦‍♂️

"Install will fail silently in Python 3 due to missing system dependencies. You may have to SSH to your pi and run the command sudo apt install libatlas3-base to get the plugin to load". **

**Comment by jneilliii** [comment]
Thanks for the suggestion. I'll take care of that.
