### ISSUE TITLE
[Suspicious Plugin Activity] RaiseCloud

### ISSUE THREAD

**Issue by wikityrey** [OctoPrint/plugins.octoprint.org#661]
Hi,
I just want to report that this plugin suddenly install without me initiating it. I was annoyed because it stopped a print that was in progress so I had to discard the partially completed print because I have no idea how to resume it. Is there a setting that I could use to prevent automatic add-on installation?

**Which Plugin? (URL to plugin page on plugin repository)**

**What's the suspicious activity?**

**Link to ticket on the plugin's issue tracker about the issue**

**Comment by foosel** [comment]
There is absolutely nothing inside OctoPrint that will just automatically install a plugin. This is exclusively done through user interaction - or rather requests on the API of the plugin manager which usually originate from the user interacting with its frontend.

If you did not initiate a plugin install, someone else did. It certainly wasn't the plugin or plugin notification, and it also wasn't OctoPrint on its own. I suggest you take a good look at who has access to your instance, remove any port forwards you might have added (and which btw are a really bad idea) and in general audit your network's security. If you need help with that, get in touch on the community forums - but be sure to include your logs, both octoprint.log and plugin_pluginmanager_console.log.
