### ISSUE TITLE
[Listing Error] Themeify has no effect on Raspberry Touchscreen

### ISSUE THREAD

**Issue by realbadfox** [OctoPrint/plugins.octoprint.org#665]
Hello,

I am using Themeify on my Octoprint and it is really great.,

It works on the webinterface via PC or Smartphone, but it doesn't work on my Raspberry PI Touchscreen.

I click on enable and restart, but it has no effect and the original theme is visualized.

can you help me please?

yours chris

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
