### ISSUE TITLE
[Abandoned Plugin] Filament Sensor Reloaded

### ISSUE THREAD

**Issue by ssorgatem** [OctoPrint/plugins.octoprint.org#687]
**Which Plugin? (URL to plugin page on plugin repository)**

https://plugins.octoprint.org/plugins/filament_sensor_reloaded/

**Ticket on plugin's issue tracker confirming abandonment:**

https://github.com/ssorgatem/Octoprint-Filament-Reloaded/issues/11

**Is there someone open to adopting it? ("no" or @-mention user):**

Maybe someone from here: https://github.com/OctoPrint/plugins.octoprint.org/issues/499

Rather than silently abandoning the plugin, I'd rather make it known as soon as possible that it needs a new maintainer, and I am willing to transfer the github repo.

Created a PR: https://github.com/OctoPrint/plugins.octoprint.org/pull/688

**Comment by AntDX316** [comment]
why abandon?? just need it to stop when filament is out

**Comment by AntDX316** [comment]
how can we add a pause stop command now?

**Comment by jneilliii** [comment]
@nickmitchko has volunteered to take over maintenance of the plugin @ssorgatem. If you would transfer the repo to them or provide access that would be the easiest transition.

**Comment by nickmitchko** [comment]
Confirming @jneilliii 's statement above

**Comment by AntDX316** [comment]
> @nickmitchko has volunteered to take over maintenance of the plugin @ssorgatem. If you would transfer the repo to them or provide access that would be the easiest transition.

does that mean the sensor stops will work again?

**Comment by ssorgatem** [comment]
Hi, sorry for not replying earlier, I just saw this.
I'll look into providing access or transferring the repo.

**Comment by ssorgatem** [comment]
@nickmitchko I added you as a collaborator, because it wouldn't let me transfer the repo because you have it already forked.

If you delete your fork I can do the transfer.

**Comment by nickmitchko** [comment]
@ssorgatem I have deleted the fork, if you prefer the transfer. I am okay with either solution

**Comment by AntDX316** [comment]
The sensor stop pause code just has to work when triggered.

**Comment by cp2004** [comment]
@AntDX316 please stop posting off-topic comments in this issue, which is about transferring the maintainer of the plugin. Thanks.
