### ISSUE TITLE
[Listing Error] EEPROM Repetier Editor

### ISSUE THREAD

**Issue by rsalach-bielecki** [OctoPrint/plugins.octoprint.org#692]
**Which Plugin? (URL to plugin page on plugin repository)**

**What's wrong with the plugin *listing*?**

**Comment by rsalach-bielecki** [comment]
New Octoprint version do not support plugins below python 3.0
Is it possible to rewrite this plugin code to python 3.x?

**Comment by cp2004** [comment]
> New Octoprint version do not support plugins below python 3.0
Completely false, and this is the wrong place to post this - thanks for closing it yourself.
