### ISSUE TITLE
[Abandoned Plugin] OctoPrint-WebcamTab

### ISSUE THREAD

**Issue by gruvin** [OctoPrint/plugins.octoprint.org#702]
There has been no response to earlier tickets since 2020-09-13 and the email address listed in setup.py bounces, "address not found". The last commit was 2018, by the looks. Hope he's OK out there somewhere. :/

**Which Plugin? (URL to plugin page on plugin repository)**

https://plugins.octoprint.org/plugins/webcamtab

**Ticket on plugin's issue tracker confirming abandonment:**
Multiple no response, including mine: https://github.com/malnvenshorn/OctoPrint-WebcamTab/issues/14 

**Is there someone open to adopting it? ("no" or @-mention user):**
@gruvin
https://github.com/gruvin/OctoPrint-WebcamTab

**Comment by jneilliii** [comment]
Your PR has been merged, closing.
