### ISSUE TITLE
[Listing Error] Printer Statistics

### ISSUE THREAD

**Issue by Flow2105** [OctoPrint/plugins.octoprint.org#729]
**https://github.com/AlexVerrico/octoprint-stats/archive/py2.zip**

*when i try to install it it takes a few minutes and then commes this
 Fehler!
Could not install plugin, unknown error, please consult octoprint.log for details
how do i upload the log

**Comment by cp2004** [comment]
Please report issues with the plugin itself to the author, linked below for your convenience:

https://github.com/AlexVerrico/octoprint-stats/

There's nothing we can do here to help here, the link works so it is an issue on the plugin's end.

**Comment by Flow2105** [comment]
what can i do to fix this ?

**Comment by jneilliii** [comment]
I see you've already opened an issue on the plugin's repository. seems like you'll have to wait for a response from the plugin maintainer.
