### ISSUE TITLE
Installs but as soon as it restarts it shows it wasn't installed[Listing Error] Octolapse

### ISSUE THREAD

**Issue by CharlosFPV** [OctoPrint/plugins.octoprint.org#730]
**Which Plugin? (URL to plugin page on plugin repository)**

**What's wrong with the plugin *listing*?**

**Comment by jneilliii** [comment]
This issue tracker is for issues with the plugin repo. If you are having issues with a plugin, please open an issue on its issue tracker, linked below for your convenience.

https://github.com/FormerLurker/Octolapse/issues
