### ISSUE TITLE
[enforced open drain please flag it properly in dt/acpi dsdt/board file] OctoPrint-Enclosure

### ISSUE THREAD

**Issue by firozdang** [OctoPrint/plugins.octoprint.org#754]
**Which Plugin? (URL to plugin page on plugin repository)**
https://github.com/vitormhenrique/OctoPrint-Enclosure

**What's wrong with the plugin *listing*?**
I connected DS18B20 sensor with pullup resisters, and after updating /boot/config with dtoverlay=w1-gpio, I cant see anything in dmesg
when I do dmesg | grep gpio, I got the following error: 
enforced open drain please flag it properly in dt/acpi dsdt/board file

Using the following sensor kit, I checked with multimeter, vcc and gnd are correctly connected, also my data signal is correctly connected on GPIO#4, PIN#16: 

https://www.banggood.com/DS18B20-Temperature-Sensor-Module-Kit-Waterproof-Electronic-Building-Block-p-1027637.html

**Comment by jneilliii** [comment]
This is not the proper place to post bugs with plugins themselves, please use the plugin's repo for that, linked below for your convenience.

https://github.com/vitormhenrique/OctoPrint-Enclosure/issues

**Comment by firozdang** [comment]
Sorry about that, thanks, will post the issue there!
