### ISSUE TITLE
Tab will not extend

### ISSUE THREAD

**Issue by matzotti** [OctoPrint/plugins.octoprint.org#77]
Hi,
the tab of theplugin will not be visible about the whole content. in my system (firefox, windows10) i can see only the lines until EEPROM Manager, no more lines...
![grafik](https://cloud.githubusercontent.com/assets/28400655/25714706/264b5fe4-30f9-11e7-998f-c0f7765ad321.png)

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it. Thanks.
