### ISSUE TITLE
[Listing Error] WebDAV Backup

### ISSUE THREAD

**Issue by MrDix** [OctoPrint/plugins.octoprint.org#773]
### Which Plugin?
WebDAV Backup

### Problem:
Failed to install

### Environment:
OctoPI Version 0.16.0, running on Raspberry Pi 3 Model B Rev 1.2
OctoPrint Version 1.5.3
Using pip of "/home/pi/oprint/bin/python2", Version 19.0.1
Installation directory: /home/pi/oprint/lib/python2.7/site-packages ("--user" flag: no)
Virtual environment: yes

### Logged error message:
```
Installing plugin from https://github.com/edekeijzer/OctoPrint-WebDavBackup/archive/main.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpHaIOiN/main.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpHaIOiN/main.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from WebDAV-Backup==0.2.1) (1.5.3)
Collecting webdavclient3 (from WebDAV-Backup==0.2.1)
Downloading https://files.pythonhosted.org/packages/9c/7f/7f5705a2684bcd42560550e7291994bbb26406f37bedc3d291ea12ece5f2/webdavclient3-3.14.5.tar.gz
Collecting lxml (from WebDAV-Backup==0.2.1)
Downloading https://files.pythonhosted.org/packages/db/f7/43fecb94d66959c1e23aa53d6161231dca0e93ec500224cf31b3c4073e37/lxml-4.6.2.tar.gz (3.2MB)
Complete output from command python setup.py egg_info:
Building lxml version 4.6.2.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rv0Smn/lxml/
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
```

### Workaround:
sudo apt-get install libxml2-dev libxslt-dev python-dev
Afterwards I was able to install the plugin with this command:
~/oprint/bin/pip install "https://github.com/edekeijzer/OctoPrint-WebDavBackup/archive/main.zip"

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
