### ISSUE TITLE
[Listing Error] Cura Thumbnails

### ISSUE THREAD

**Issue by hunterwlodarczyk1** [OctoPrint/plugins.octoprint.org#775]
**Which Plugin? (URL to plugin page on plugin repository)**

**What's wrong with the plugin *listing*?**
when i try to add this plug-in to my octoprint using the url, it says my system is being throttled and wont install the plug-in

**Comment by cp2004** [comment]
That is not a problem with the plugin repository, but instead a problem with your setup. You need to fix the throttling of your system before you can install plugins. There is no problem with the plugin either.

**Comment by hunterwlodarczyk1** [comment]
Ok,thank you
