### ISSUE TITLE
[Listing Error] OctoBuddy - Default configured IO breaks other plugins 

### ISSUE THREAD

**Issue by RFBomb** [OctoPrint/plugins.octoprint.org#776]
**Which Plugin? (URL to plugin page on plugin repository)**

https://plugins.octoprint.org/plugins/OctoBuddy/

**What's wrong with the plugin *listing*?**

https://github.com/mlo821/OctoBuddy/issues/10

A warning should be added that default GPIO is configured and may conflict with other plugins until the developer fixes their plugin by disabling the defaults.

**Comment by jneilliii** [comment]
You've done the proper thing by submitting this to @mlo821 issue tracker. We don't change the plugin's listing here without the plugin authors consent or if something needs to get fixed relative to the actual listing (incorrect URL to plugin, etc.) in the repo here.
