### ISSUE TITLE
[Listing Error] OctoPrint-Tplinkautoshutdown

### ISSUE THREAD

**Issue by Bostjan35** [OctoPrint/plugins.octoprint.org#794]
**Which Plugin?**

https://plugins.octoprint.org/plugins/TpLinkAutoShutdown/

**What kind of listing error are you reporting?**

a typo in the plugin listing

By Installing Plugins I get Error:
Installing plugin from https://github.com/jamesmccannon02/OctoPrint-Tplinkautoshutdown/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpfKOPQy/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpfKOPQy/master.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Tplinkautoshutdown==0.2.1) (1.5.3)
ERROR: Could not find a version that satisfies the requirement python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1) (from versions: none)
ERROR: No matching distribution found for python-kasa (from OctoPrint-Tplinkautoshutdown==0.2.1)
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by cp2004** [comment]
This plugin is only Python 3 compatible, and it is stated in the plugin listing:
![image](https://user-images.githubusercontent.com/31997505/109045999-2ae52b80-76cc-11eb-958e-98a297ae4f95.png)
