### ISSUE TITLE
[Abandoned Plugin] OctoPrint-Slack

### ISSUE THREAD

**Issue by awenelo** [OctoPrint/plugins.octoprint.org#797]
**Which Plugin?**

https://plugins.octoprint.org/plugins/slack/

**Link to ticket on plugin's issue tracker confirming abandonment**

richjoyce/OctoPrint-Slack#17
No response in 16 days,
No response to bug reports:
richjoyce/OctoPrint-Slack#16
No response to Python3 compatibility requests:
richjoyce/OctoPrint-Slack#15
richjoyce/OctoPrint-Slack#13

**Is there someone open to adopting it?**

Don't think so

**Comment by mkevenaar** [comment]
I am willing to try to maintain this. How do I get started?

**Comment by jneilliii** [comment]
The first step would be creating a fork of the plugin and update all its software update hooks and such to point to your repo on github. Then make whatever necessary changes are there for python 3 compatibility and release a new version updating the setup.py file with the new version. Once that is done, submit a PR against this repo changing the plugin's listing file to point to your github repo, add the authors: list to include yourself. We can help you through these last steps as part of our review of your PR.

**Comment by mkevenaar** [comment]
I can do that, will be working on that tomorrow! Thanks
