### ISSUE TITLE
[Listing Error] PrintJobHistory not working

### ISSUE THREAD

**Issue by Patrickbusse** [OctoPrint/plugins.octoprint.org#815]
### Which Plugin?

https://plugins.octoprint.org/plugins/PrintJobHistory/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

Hello,
I try to use the plugin but i dont know how. I installed it via plugin manager and run a couple prints. None of the prints got captured. Can someone give me an How to or an advise ?

**Comment by cp2004** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!

Thanks :)
