### ISSUE TITLE
[Listing Error] WiFi Status

### ISSUE THREAD

**Issue by MathPicussa** [OctoPrint/plugins.octoprint.org#827]
### Which Plugin?

https://plugins.octoprint.org/plugins/wifistatus/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

I could not install this plugin.
Error message:
Installing plugin from https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/archive/master.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpKaAcoH/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpKaAcoH/master.zip
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-SfuKUw/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-SfuKUw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-SfuKUw/pip-egg-info
cwd: /tmp/pip-req-build-SfuKUw/
Complete output (6 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-req-build-SfuKUw/setup.py", line 6
plugin_package = f"octoprint_{plugin_identifier}"
^
SyntaxError: invalid syntax
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by cp2004** [comment]
This plugin is not compatible with your system - it requires Python 3.7 or greater.

![image](https://user-images.githubusercontent.com/31997505/111887018-2873aa00-89ca-11eb-86bb-c5eb30fb490a.png)


Please read the information in the plugin listing *first* before opening issues here.

In addition, problems installing the plugin should go to the author, not here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!
