### ISSUE TITLE
Usage stats of plugins with uppercase ID are wrong

### ISSUE THREAD

**Issue by NilsRo** [OctoPrint/plugins.octoprint.org#830]
Hi. I like to document this error discussed in the Forum as I did not find an issue corresponding. 

https://community.octoprint.org/t/plugin-repo-new-installs-the-past-week-stays-on-0/31428

Plugins with capital letters in the ID does not count new installations. It is 0 constantly.

**Comment by foosel** [comment]
Well, not with the repository, but the export scripts it uses (as pointed out by @cp2004). In any case, fixed now as of https://github.com/OctoPrint/tracking.octoprint.org/commit/6597a94cd14fa7b8d06033e09f9f06008a9f7ab5

There's still a bit of a general open question whether plugin identifiers should always be treated as lower case or not, and I'm still unsure whether this can be fixed without breaking stuff all across the board, but at least this annoyance is now taken care of quite more easily than I thought it would be.
