### ISSUE TITLE
[Listing Error] OctoPrint-TPLinkSmartplug

### ISSUE THREAD

**Issue by WOODPRO** [OctoPrint/plugins.octoprint.org#831]
### Which Plugin?

https://plugins.octoprint.org/plugins/tplinksmartplug/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

Pugin is a answer to  PROBLEM IN SAFELY POWERING OF MY ENDER 3 V2.

I have a question about interfacing with a BTT smart filament sensor.  if the filament if broken or stuck and the printer retracts the filament, how do I prevent a shutdown while the machine is waiting on me to replace the clogged nozzle of the filament so I don't loose the entire print?  Its difficult to set this up for a test, so, I thought I'd ask the question.  I also discovered that you can't use PSU control with your app because the system usually starts with the PSU off whic is sensed by your plugin a it issues a shutdown.

Also does the Raspberry pi shutdown system command get triggered even from the icon button?

Thanks for a great safety plugin.

**Comment by cp2004** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!

Thanks :)
