### ISSUE TITLE
[Listing Error] OctoText

### ISSUE THREAD

**Issue by Depdog028** [OctoPrint/plugins.octoprint.org#839]
### Which Plugin?

https://plugins.octoprint.org/plugins/OctoText/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

Installing plugin from https://github.com/berrystephenw/OctoText/archive/refs/heads/main.zip...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpC9blOT/main.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpC9blOT/main.zip
ERROR: Package 'OctoPrint-OctoText' requires a different Python: 2.7.16 not in '>=3, <4'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jneilliii** [comment]
OctoText is listed as Python 3 only, so the error you are receiving is because you're trying to install manually and is the expected result.

https://plugins.octoprint.org/plugins/OctoText/
