### ISSUE TITLE
Adoption of CR-10 Leveling plugin

### ISSUE THREAD

**Issue by electr0sheep** [OctoPrint/plugins.octoprint.org#843]
[CR-10 Leveling Plugin](https://github.com/electr0sheep/OctoPrint-Cr10_leveling)

I originally created this plugin years ago, and don't really have time to maintain it any more.

I am looking for someone who wants to take ownership of this plugin. If you are interested, please leave a comment here.

Thanks!

**Comment by lsellens** [comment]
If no one else is interested I can take over. I use this plugin all of the time so I don't see myself abandoning it anytime soon.

**Comment by jneilliii** [comment]
Thanks @lsellens. The easiest way to transition this is to either have @electr0sheep transfer the repo to your github account, or add you as a maintainer to his repo. Once that's done I can remove the adandoned flag.

**Comment by AvanOsch** [comment]
I basically feel the same as @lsellens.
@electr0sheep, maybe you can transfer to one of us, and make the other a maintainer?

**Comment by icancwhatusay** [comment]
Well sadly I don't know enough about how to maintain such things but I have found this plug-in to be wonderfully simple, easy to use and incredibly useful so thank you for creating it in the first place.

**Comment by electr0sheep** [comment]
@lsellens If you will delete the fork you have, I will transfer ownership to you. It won't currently allow me to do it because you already have a repo with the same name.

**Comment by lsellens** [comment]
@electr0sheep done

**Comment by electr0sheep** [comment]
@lsellens Transfer has been initiated. I think you just need to "accept" the transfer now or something

**Comment by lsellens** [comment]
Cool thanks, Ill keep it alive. @AvanOsch I sent you an invite to be added as a maintainer.

**Comment by lsellens** [comment]
@jneilliii you can close this and remove the abandoned flag

**Comment by jneilliii** [comment]
@lsellens make sure to adjust the url's in the repo to your github account. The repo transfer will handle software update stuff for future versions, but would be good to have that in place for new installs. Thanks for the smooth transition @electr0sheep.
