### ISSUE TITLE
[Listing Error] PSU Control

### ISSUE THREAD

**Issue by manueloya** [OctoPrint/plugins.octoprint.org#846]
### Which Plugin?

https://plugins.octoprint.org/plugins/psucontrol/

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

the  sensing works but the Switching doesnt work , using gpio option doent work (with the last version) and with the plugin rpi gpio , doesnt work too

**Comment by jneilliii** [comment]
This is the issue tracker for the plugin repository, not for support directly with plugins. Please see the issues on that plugin's repository, there are some fixes that were pushed recently and additional information provided.

https://github.com/kantlivelong/OctoPrint-PSUControl
