### ISSUE TITLE
I have an issue with Octoprint, Loaded the command control editor.

### ISSUE THREAD

**Issue by CookieMan66** [OctoPrint/plugins.octoprint.org#86]
What kinds of issues you should report here:

  * missing or broken homepage, source or download URLs
  * broken images
  * incorrect compatibility information
  * ... in short, anything related to the data on plugins.octoprint.org

What you should not report here:

  * Any kinds of issues with the plugins themselves - report those
    to the plugin author instead!

Thanks :)

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it. Thanks.
