### ISSUE TITLE
lick on it i get the green box and select it. Then right click i get create container. But no window opens up. I am using OctoPrint 1.3.4

### ISSUE THREAD

**Issue by CookieMan66** [OctoPrint/plugins.octoprint.org#87]
What kinds of issues you should report here:

  * missing or broken homepage, source or download URLs
  * broken images
  * incorrect compatibility information
  * ... in short, anything related to the data on plugins.octoprint.org

What you should not report here:

  * Any kinds of issues with the plugins themselves - report those
    to the plugin author instead!

Thanks :)

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it. Thanks.
