### ISSUE TITLE
[Listing Error] Octoprint Youtube Timelapse

### ISSUE THREAD

**Issue by GutlessGnat** [OctoPrint/plugins.octoprint.org#872]
### Which Plugin?

https://plugins.octoprint.org/plugins/youtube_timelapse/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

When it auto uploads it restricts it for terms and policies and won't allow me to amend it ?

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
