### ISSUE TITLE
[Listing Error] OctoPrint-CustomBackground

### ISSUE THREAD

**Issue by Lanzentraeger** [OctoPrint/plugins.octoprint.org#873]
### Which Plugin?

https://plugins.octoprint.org/plugins/custombackground/

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

Today i got the new Octoprint Update. Since the Update, my Custom Background GIF is not running smooth. Before it was very smooth, now there is a long cut when it starts again and again. Also the Time for the GIF is reduced, before it has played all the length the GIF had. There is a random issue and the time is to short now for me. Thanks, greetings Chris

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
