### ISSUE TITLE
[Listing Error] Calibration Companion

### ISSUE THREAD

**Issue by maconly34** [OctoPrint/plugins.octoprint.org#879]
### Which Plugin?

https://plugins.octoprint.org/plugins/calibrationcompanion/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

Could not fetch plugin from server, got 404 Client Error: Not Found for url: https://codeload.github.com/iFrostizz/OctoPrint-CalibrationCompanion/zip/master

**Comment by cp2004** [comment]
See https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/issues/1

It was fixed quickly, but you probably need to refresh.
