### ISSUE TITLE
[Listing Error] OctoRelay

### ISSUE THREAD

**Issue by williamn79** [OctoPrint/plugins.octoprint.org#890]
### Which Plugin?

https://plugins.octoprint.org/plugins/octorelay/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

Installing plugin "OctoRelay" from https://github.com/borisbu/OctoRelay/archive/master.zip...
/home/pi/oprint/bin/python -m pip --disable-pip-version-check install file:///tmp/tmpgobgeh2z/OctoRelay-master.zip --no-cache-dir
Processing /tmp/tmpgobgeh2z/OctoRelay-master.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.8/site-packages (from OctoRelay==1.1.0) (1.6.1)
Collecting RPi.GPIO
Downloading RPi.GPIO-0.7.0.tar.gz (30 kB)
Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.10.4)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.5.0)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.20.3)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.2.4 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2021.2.4)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.1.0)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2021.4.4)
Requirement already satisfied: wrapt<2,>=1.12.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.12.1)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2021.2.23)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.1.1)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (3.5)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (3.1.1)
Requirement already satisfied: feedparser<7,>=6.0.2 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (6.0.2)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.0.1)
Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.6.0)
Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.1.4)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.4.21)
Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (7.1.2)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.2.0)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.1.5.post0)
Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.1.1)
Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.10.9)
Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2.11.3)
Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.59.0)
Requirement already satisfied: OctoPrint-PiSupport>=2021.3.26 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2021.3.26.post2)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.0.7)
Requirement already satisfied: PyYAML<6,>=5.3.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (5.4.1)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2.8.5)
Requirement already satisfied: zipstream-new<1.2,>=1.1.8 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.1.8)
Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (5.8.0)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.0.0)
Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.8.0)
Requirement already satisfied: requests<3,>=2.23.0 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2.25.1)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.18.2)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.4)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.7.0)
Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (5.1.1)
Requirement already satisfied: zeroconf<0.25,>=0.24 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (0.24.5)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (2.0)
Requirement already satisfied: immutabledict<2,>=1.2.0 in /home/pi/oprint/lib/python3.8/site-packages (from OctoPrint->OctoRelay==1.1.0) (1.3.0)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python3.8/site-packages (from watchdog==0.10.4->OctoPrint->OctoRelay==1.1.0) (0.1.2)
Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.8/site-packages (from feedparser<7,>=6.0.2->OctoPrint->OctoRelay==1.1.0) (1.0.0)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.8/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoRelay==1.1.0) (2.0)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.8/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoRelay==1.1.0) (2.9.1)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.8/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoRelay==1.1.0) (2021.1)
Requirement already satisfied: setuptools>=36 in /home/pi/oprint/lib/python3.8/site-packages (from markdown<3.2,>=3.1->OctoPrint->OctoRelay==1.1.0) (44.0.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/pi/oprint/lib/python3.8/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoRelay==1.1.0) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.8/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoRelay==1.1.0) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python3.8/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoRelay==1.1.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python3.8/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoRelay==1.1.0) (1.26.4)
Requirement already satisfied: six in /home/pi/oprint/lib/python3.8/site-packages (from websocket-client<1,>=0.57->OctoPrint->OctoRelay==1.1.0) (1.16.0)
Requirement already satisfied: ifaddr in /home/pi/oprint/lib/python3.8/site-packages (from zeroconf<0.25,>=0.24->OctoPrint->OctoRelay==1.1.0) (0.1.7)
Building wheels for collected packages: OctoRelay, RPi.GPIO
Building wheel for OctoRelay (setup.py): started
Building wheel for OctoRelay (setup.py): finished with status 'done'
Created wheel for OctoRelay: filename=OctoRelay-1.1.0-py2.py3-none-any.whl size=14017 sha256=bb5ad0ba3dbed8c5387d5c7de5d2a16d127d1100a95ee71faf82b3193cfbab0c
Stored in directory: /tmp/pip-ephem-wheel-cache-wgy9oapp/wheels/24/b3/d0/108e4b26b898575534ac06166fa0b294d39f344350d15144bf
Building wheel for RPi.GPIO (setup.py): started
Error!
Could not install plugin from https://github.com/borisbu/OctoRelay/archive/master.zip, see the log for more details

**Comment by cp2004** [comment]
Please report issues with individual plugins to the plugin's own repository, there is nothing we can do about this here. Alternatively, state what is wrong with the actual information on the listing.

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!
