### ISSUE TITLE
[Listing Error] OctoPrint-WideScreen

### ISSUE THREAD

**Issue by orkusmg** [OctoPrint/plugins.octoprint.org#892]
### Which Plugin?

https://plugins.octoprint.org/plugins/widescreen/

### What kind of listing error are you reporting?

broken images on the listing

### What specifically is broken or wrong?

Plugin does not detect any sections
![2021-05-29_08h19_17](https://user-images.githubusercontent.com/49352823/120060196-9e456300-c056-11eb-894f-903623d37fc6.png)
. There is nothing to drag from left to right

System info:
browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
connectivity.connection_check: 1.1.1.1:53
connectivity.connection_ok: true
connectivity.enabled: false
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1500
env.hardware.ram: 3959984128
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 4 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.18.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.3.3
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.6.1
printer.firmware: Klipper
systeminfo.generator: systemapi

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
