### ISSUE TITLE
It keeps freezing on my iphone.  How do I remove it?

### ISSUE THREAD

**Issue by whb52ford** [OctoPrint/plugins.octoprint.org#893]
### Which Plugin?

https://plugins.octoprint.org/plugins/uicustomizer/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

It keeps freezing on my iphone.  Screen locks and can't do anything.  How do I remove this?  thx

**Comment by cp2004** [comment]
Please report issues with individual plugins to the plugin's own repository, and seek support on the [community forums](https://community.octoprint.org) or [discord server](https://discord.octoprint.org). Thanks!

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!
