### ISSUE TITLE
[Feature Request] Add sort by number of installations

### ISSUE THREAD

**Issue by gobbledygoober** [OctoPrint/plugins.octoprint.org#900]
### What do you want to see implemented in the plugin repository?

Suggest that "Sort By" active or total installations be added to complement Name, Date, Tag, and Author.

### Why, what problems would be solved by this?

This would be helpful to show new users which plugins are popular. Instead, I looked for articles on the internet that recommended plugins and looked at the raw json export "instances" statistics.

**Comment by cp2004** [comment]
If I remember right there is already a sort option in the plugin manager actually inside OctoPrint, just not on the website.

**Comment by jneilliii** [comment]
Yeah, I think the default sort order in get more of plugin manager was changed to sort by number of installs.

**Comment by gobbledygoober** [comment]
Aha! I see it now. Thanks!
