### ISSUE TITLE
[Listing Error] OctoPrint-GpioRgbController

### ISSUE THREAD

**Issue by Athanaetos** [OctoPrint/plugins.octoprint.org#908]
### Which Plugin?

https://plugins.octoprint.org/plugins/gpiorgbcontroller/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

Whenever I enable this plugin, my octoprint crashes. The wifi seems to die. I need to plug it into an ethernet, then disable it. Afterwards I can use wifi.

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
