### ISSUE TITLE
Not triggering events at all,  OctoPrint-IFTTT

### ISSUE THREAD

**Issue by CodfishCatfish** [OctoPrint/plugins.octoprint.org#922]
### Which Plugin?

https://plugins.octoprint.org/plugins/IFTTT/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

Will not trigger IFTTT events.

**Comment by cp2004** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered within it.

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!

Thanks :)
