### ISSUE TITLE
[Listing Error] Octoprint Youtube Timelapse

### ISSUE THREAD

**Issue by hryanl** [OctoPrint/plugins.octoprint.org#938]
### Which Plugin?

https://plugins.octoprint.org/plugins/youtube_timelapse/

### What kind of listing error are you reporting?

incorrect compatibility information on the plugin listing

### What specifically is broken or wrong?

This plugin will not allow you to publish your uploaded videos as public videos. In fact, if you try to do so, YouTube will lock the video to private permanently because the videos are being uploaded via an unverified API service. It appears that the developer does not consider this an issue because 'it still allows you to upload videos as private'. There is no notice from the plugin that it will not function as intended for most people.

**Comment by jneilliii** [comment]
---

Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it:

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!
