### ISSUE TITLE
[Listing Error] Fullscreen Webcam

### ISSUE THREAD

**Issue by DrQbz** [OctoPrint/plugins.octoprint.org#962]
### Which Plugin?

https://plugins.octoprint.org/plugins/fullscreen/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

It is not possible to install plugin. 
There are 0 active instances and 0 new installs.  

Broken plugin?

**Comment by cp2004** [comment]
> There are 0 active instances and 0 new installs.

Just fixed this - the plugin's ID was not matching up, now it is and there are stats showing.

If you are having trouble installing it, reach out on the community forums, discord server or the plugin's own issue tracker, as we can't resolve those issues here.
