### ISSUE TITLE
[movimento fallito] Bed Leveling

### ISSUE THREAD

**Issue by caos86** [OctoPrint/plugins.octoprint.org#964]
### Which Plugin?

https://plugins.octoprint.org/plugins/CR10_Leveling/

### What kind of listing error are you reporting?

a typo in the plugin listing

### What specifically is broken or wrong?

salve questo plugin dall ultimo aggiornamento non a piu i movimenti dei 5 punti  una volta che il bed arriva a temperatura invece di livellare compare la scritta stampa

**Comment by cp2004** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin repository, not issues with the plugins registered in it.

> What kinds of issues you should report here:
> 
> * missing or broken homepage, source or download URLs
> * broken images
> * incorrect compatibility information
> * ... in short, anything related to the data on plugins.octoprint.org
> 
> What you should not report here:
> 
> * Any kinds of issues with the plugins themselves - report those to the plugin author instead!

Thanks
