### ISSUE TITLE
Rotate rectangles exclude region 

### ISSUE THREAD

**Issue by Tlumppy01** [OctoPrint/plugins.octoprint.org#969]
### What do you want to see implemented in the plugin repository?

As a core x/y user, I print most prints at a 45 degree angle, It would be helpful to be able to rotate the exclude region . Thanks

### Why, what problems would be solved by this?

as it stands I need to use multiple rectangular and circular regions to exclude a part on a 45 degree angle

### Any additional information you want to provide?

love this product!  can a make a donation?

**Comment by kantlivelong** [comment]
This tracker is reserved for:

- missing or broken homepage, source or download URLs
broken images
- incorrect compatibility information
- ... in short, anything related to the data on plugins.octoprint.org

If this issue only applies to a specific plugin please report to the appropriate plugin repository.

If this issue affects all plugins please submit a ticket to https://github.com/foosel/OctoPrint
