### ISSUE TITLE
More than one hotend

### ISSUE THREAD

**Issue by albinger** [OctoPrint/plugins.octoprint.org#97]
The plugin only displays one of my hotends and not the one I'm typically using.

Can it be updated to show all hotends or allow me to configure which one gets presented?

**Comment by foosel** [comment]
Please report issues with specific plugins in the bug tracker of the plugin instead of here. This tracker is for reporting issues with the plugin **repository**, not issues with the plugins registered in it, as also stated on the ticket form:

> What kinds of issues you should report here:
>
>   * missing or broken homepage, source or download URLs
>   * broken images
>   * incorrect compatibility information
>   * ... in short, anything related to the data on plugins.octoprint.org
>
> What you should not report here:
>
>   * Any kinds of issues with the plugins themselves - report those
>     to the plugin author instead!

Thanks :)
