### ISSUE TITLE
[Listing Error] Blocks

### ISSUE THREAD

**Issue by zerneo85** [OctoPrint/plugins.octoprint.org#972]
### Which Plugin?

https://plugins.octoprint.org/plugins/BLOCKS/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

The download and install link to the master is not working. The install file is not found.

![image](https://user-images.githubusercontent.com/5507607/147388651-e556eb9e-c4a5-4591-9509-d79c99af1d4f.png)

**Comment by jneilliii** [comment]
Thanks, fixed with commit https://github.com/OctoPrint/plugins.octoprint.org/commit/b4f3f91a381aa1ea16b6354f4d6415186af32be9
