### ISSUE TITLE
[Listing Error] MetadataPreprocessor

### ISSUE THREAD

**Issue by CyFire** [OctoPrint/plugins.octoprint.org#996]
### Which Plugin?

https://plugins.octoprint.org/plugins/metadatapreprocessor/

### What kind of listing error are you reporting?

broken link on the listing

### What specifically is broken or wrong?

Can't install from the address given.

**Comment by awenelo** [comment]
It looks like I was missing `release.zip` in the latest release. I've added it now, and the link works for me.

@CyFire, could you try installing again?

**Comment by CyFire** [comment]
It works now.  Thanks.
