### ISSUE TITLE
[Abandoned Plugin] LEDStripControl

### ISSUE THREAD

**Issue by Cpmjaguar1234** [OctoPrint/plugins.octoprint.org#999]
### Which Plugin?

https://plugins.octoprint.org/plugins/ledstripcontrol/

### Link to ticket on plugin's issue tracker confirming abandonment

It says it on the octoprint details page

### Is there someone open to adopting it?

@cpmjaguar1234

**Comment by Cpmjaguar1234** [comment]
![Screenshot 2022-01-26 10 23 51 PM](https://user-images.githubusercontent.com/93066433/151286492-8ee756c2-6810-46f5-8769-dbf749973f41.png)

**Comment by jneilliii** [comment]
duplicate of #918
